---

- name: register service
  shell:
    /usr/sbin/update-service --add {{ tinydns.supervise_dir }}/{{ tinydns.service_name }}
  when: serviceRegistered|failed

- name: restart service
  shell:
    /usr/sbin/update-service --remove {{ tinydns.supervise_dir }}/{{ tinydns.service_name }} &&
    /usr/sbin/update-service --add {{ tinydns.supervise_dir }}/{{ tinydns.service_name }}
  when: serviceRegistered|success