---
# Users and Groups creation
- name: stop {{ galaxie_qmail_server_service_send }}
  service:
    name="{{ galaxie_qmail_server_service_send }}"
    state=stopped

- name: create groups
  group:
    name={{ item }}
    state=present
    system=yes
  with_items:
    - "{{ galaxie_qmail_server_qmail_group }}"
    - "{{ galaxie_qmail_server_nofiles_group }}"

- name: create users
  user:
    name={{ item.username }}
    system=yes
    createhome=no
    home={{ galaxie_qmail_server_qmail_dir }}
    state=present
    group={{ item.group }}
  with_items:
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: "{{ galaxie_qmail_server_qmaild_user }}" }
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: "{{ galaxie_qmail_server_qmaill_user }}" }
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: "{{ galaxie_qmail_server_qmailp_user }}" }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: "{{ galaxie_qmail_server_qmailq_user }}" }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: "{{ galaxie_qmail_server_qmailr_user }}" }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: "{{ galaxie_qmail_server_qmails_user }}" }

- name: create user '{{ galaxie_qmail_server_alias_user }}'
  user:
    name="{{ galaxie_qmail_server_alias_user }}"
    system=yes
    createhome=no
    home="{{ galaxie_qmail_server_qmail_dir }}/alias"
    state=present
    group="{{ galaxie_qmail_server_nofiles_group }}"

- name: check {{ galaxie_qmail_server_qmail_dir }}/alias directory
  file:
    path="{{ galaxie_qmail_server_qmail_dir }}/alias"
    state=directory
    owner="{{ galaxie_qmail_server_alias_user }}"
    group="{{ galaxie_qmail_server_qmail_group }}"
    mode=2755

# Installation
- name: packages for qmail building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - daemontools
    - daemontools-run
    - passwd
    - libssl-dev
    - libperl-dev

- name: check {{ galaxie_qmail_server_source_dir }} directory
  file:
    path={{ galaxie_qmail_server_source_dir }}
    state=directory
    owner=root
    group=root
    mode=0755

- name: get qmail sources
  get_url:
    url=http://cr.yp.to/software/qmail-1.03.tar.gz
    dest="{{ galaxie_qmail_server_source_dir }}"
    sha256sum=21ed6c562cbb55092a66197c35c8222b84115d1acab0854fdb1ad1f301626f88
  register: qmail_download

- name: empty build directory
  file:
    path={{ item }}
    state=absent
    force=yes
  with_items:
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03'
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10'
  when: qmail_download.changed

- name: Unarchive {{ qmail_download.dest }}
  unarchive:
    src="{{ qmail_download.dest }}"
    dest="{{ galaxie_qmail_server_source_dir }}"
    copy=no
  when: qmail_download.changed

- name: send qmail-1.03-jms1-7.10.patch to "{{ galaxie_qmail_server_source_dir }}"
  copy:
    src=qmail-1.03-jms1-7.10.patch
    dest="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10.patch"

#- name: get qmail patches
#  get_url:
#    url=http://qmail.jms1.net/patches/qmail-1.03-jms1-7.10.patch
#    dest="{{ galaxie_qmail_server_source_dir }}"
#    sha256sum=3807b4adfc7dbf83e3e2e9e0c841b3443e3bc468bc91ffd240dd420a7fcaa84b
#  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed

- name: apply qmail patches
  shell: patch < {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10.patch
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03"
  changed_when: false
  when: qmail_download.changed

- name: rename {{ galaxie_qmail_server_source_dir }}/qmail-1.03 to {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10
  shell: mv {{ galaxie_qmail_server_source_dir }}/qmail-1.03 {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10
  changed_when: false
  when: qmail_download.changed

- name: build qmail-1.03-jms1-7.10
  shell: make
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  changed_when: false

- name: install qmail manuel
  shell: make man
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  changed_when: false

- name: install qmail-1.03-jms1-7.10
  shell: make setup check
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  changed_when: false

###############################################################################
#
# system - Preparing system for launch
#
- name: check supervise dir
  file:
    path={{ galaxie_qmail_server_supervise_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
