- hosts: galaxie
  sudo: true
  tasks:
   - name: Update Apt
     apt: update_cache=yes cache_valid_time=3600
   - name: Install required software
     action: apt pkg={{item}} state=installed
     with_items:
      - bash-completion
      - dnsutils
      - htop
      - module-assistant  
      - git
      - wget
      - vim
      - mc
      - ntp
      - rsync
      - sshfs
      - screen
      - minicom
   - name: Remove not require software
     action: apt pkg={{item}} state=absent purge=yes
     with_items:
      - nano
      - emacs
      - ntpdate
      - nfs-common
      - nfs-kernel-server
      - rpcbind
