---
- name: Add Tvheadend Debian 8 key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
  failed_when: "keyExists.rc == 2"
  changed_when: false
  register: keyExists
  when: ansible_distribution == "Debian"

- name: activate Debian Tvheadend repository
  apt_repository:
    repo="deb http://dl.bintray.com/tvheadend/deb jessie stable"
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: activate Debian Tvheadend repository
  apt_repository:
    repo="deb http://dl.bintray.com/tvheadend/deb wheezy stable"
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- name: update apt cache
  apt: update_cache=yes

- name: check Tvheadend packages are present
  apt:
    pkg="{{item}}"
    state=installed
  with_items:
    - hdhomerun-config
    - libhdhomerun-dev
    - libhdhomerun1
    - tvheadend