---

- name: test if we can resolv "{{ galaxie_dnscache_client_host_for_test }}" via {{ galaxie_dnscache_client_bind_interface }}
  shell: "host {{ galaxie_dnscache_client_host_for_test }} {{ galaxie_dnscache_client_bind_interface }}"
  changed_when: False
  register: ResolverCheck

- name: Enable local server name resolution via DNSCache
  template:
    src=resolv.conf.j2
    dest=/etc/resolv.conf
    backup=yes
  when: "ResolverCheck.rc == 0"

- name: Remove resolvconf
  apt:
    name: resolvconf
    state: absent
  when: "ResolverCheck.rc == 0"

- name: Delete "domain-name" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_rm.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-name
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: galaxie_dnscache_client_set_domain

- name: Add "domain-name" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_add.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-name
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not galaxie_dnscache_client_set_domain

- name: Delete "domain-name-servers" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_rm.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-name-servers
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: galaxie_dnscache_client_set_nameservers

- name: Add "domain-name-servers" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_add.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-name-servers
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not galaxie_dnscache_client_set_nameservers

- name: Delete "domain-search" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_rm.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-search
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: galaxie_dnscache_client_set_searchs

- name: Add "domain-search" inside {{ galaxie_dnscache_client_dhclient_file }}
  script: dhclient_add.sh {{ galaxie_dnscache_client_dhclient_file }} request domain-search
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not galaxie_dnscache_client_set_searchs
