---

- name: test if we can resolv "{{ galaxie.dnscache.host_for_test }}" via {{ galaxie.dnscache.interface }}
  shell: "host {{ galaxie.dnscache.host_for_test }} {{ galaxie.dnscache.interface }}"
  changed_when: False
  register: ResolverCheck

- name: Enable local server name resolution via DNSCache
  template:
    src=resolv.conf.j2
    dest=/etc/resolv.conf
    backup=yes
  when: "ResolverCheck.rc == 0"

- name: Remove resolvconf
  apt:
    name: resolvconf
    state: absent
  when: "ResolverCheck.rc == 0"

#- name: add key to dhclient.conf
#  script: dhclient_add.sh /etc/dhcp/dhclient.conf request domain-name
#  register: dhclient_key_insertion
#  changed_when: dhclient_key_insertion.rc == 0
#  failed_when: dhclient_key_insertion.rc >= 2
