---

- name: test if we can resolv "{{ host_for_test }}" via {{ bind_interface }}
  shell: "host {{ host_for_test }} {{ bind_interface }}"
  changed_when: False
  register: ResolverCheck

- name: Enable local server name resolution via DNSCache
  template:
    src=resolv.conf.j2
    dest=/etc/resolv.conf
    backup=yes
  when: "ResolverCheck.rc == 0"

- name: Remove resolvconf
  apt:
    name: resolvconf
    state: absent
  when: "ResolverCheck.rc == 0"

- name: Delete "domain-name" inside {{ dhclient_file }}
  script: dhclient_rm.sh {{ dhclient_file }} request domain-name
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: set_domain

- name: Add "domain-name" inside {{ dhclient_file }}
  script: dhclient_add.sh {{ dhclient_file }} request domain-name
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not set_domain

- name: Delete "domain-name-servers" inside {{ dhclient_file }}
  script: dhclient_rm.sh {{ dhclient_file }} request domain-name-servers
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: set_nameservers

- name: Add "domain-name-servers" inside {{ dhclient_file }}
  script: dhclient_add.sh {{ dhclient_file }} request domain-name-servers
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not set_nameservers

- name: Delete "domain-search" inside {{ dhclient_file }}
  script: dhclient_rm.sh {{ dhclient_file }} request domain-search
  register: dhclient_key_remove
  changed_when: dhclient_key_remove.rc == 0
  failed_when: dhclient_key_remove.rc >= 2
  when: set_searchs

- name: Add "domain-search" inside {{ dhclient_file }}
  script: dhclient_add.sh {{ dhclient_file }} request domain-search
  register: dhclient_key_insertion
  changed_when: dhclient_key_insertion.rc == 0
  failed_when: dhclient_key_insertion.rc >= 2
  when: not set_searchs
