---

- name: Check directorys
  file:
    path="{{item}}"
    owner=root
    group=root
    state=directory
    mode=0755
  with_items:
    - "{{ galaxie_mozilla_firefox_cache_dir }}"
    - "{{ galaxie_mozilla_firefox_opt_dir }}"

- name: Check for last version
  script: get_basename_by_url.sh '{{ galaxie_mozilla_firefox_downloader_url }}'
  register: galaxie_mozilla_firefox_filename
  failed_when: not galaxie_mozilla_firefox_filename.stdout
  changed_when: False

#- debug: msg="{{ galaxie_mozilla_firefox_filename.stdout_lines[0] }}"

- name: Download {{ galaxie_mozilla_firefox_filename.stdout_lines[0] }}
  get_url:
    url="{{ galaxie_mozilla_firefox_downloader_url }}"
    dest="{{ galaxie_mozilla_firefox_cache_dir }}/{{ galaxie_mozilla_firefox_filename.stdout_lines[0] }}"
  when: galaxie_mozilla_firefox_downloader_url and galaxie_mozilla_firefox_filename
  register: galaxie_mozilla_firefox_download
  failed_when: not galaxie_mozilla_firefox_downloader_url

#- debug: msg="{{ galaxie_mozilla_firefox_download }}"

- name: Delete {{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}
  file:
    path={{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}
    state=absent
  when: galaxie_mozilla_firefox_download.changed

- name: Unarchive {{ galaxie_mozilla_firefox_download.dest }}
  unarchive:
    src="{{ galaxie_mozilla_firefox_download.dest }}"
    dest="{{ galaxie_mozilla_firefox_opt_dir }}"
    copy=no
  when: galaxie_mozilla_firefox_download.changed

- name: Set permissions of {{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}
  file:
    path={{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}
    owner=root
    group=root
    state=directory
    mode=0755

- name: Set permissions of {{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}/
  file:
    path={{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}
    owner=root
    group=root
    recurse=yes

- name: Check /usr/bin/{{ galaxie_mozilla_firefox_app_name }} link
  stat: path=/usr/bin/{{ galaxie_mozilla_firefox_app_name }}
  register: links

#- debug: msg="{{ links.stat.lnk_source }}"

- name: Delete previus /usr/bin/{{ galaxie_mozilla_firefox_app_name }}
  file:
    path=/usr/bin/{{ galaxie_mozilla_firefox_app_name }}
    state=absent
  when: links.stat.lnk_source != "{{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}/{{ galaxie_mozilla_firefox_app_name }}" or links.stat.islnk != true

- name: Create symbolic link
  file:
    src="{{ galaxie_mozilla_firefox_opt_dir }}/{{ galaxie_mozilla_firefox_app_name }}/{{ galaxie_mozilla_firefox_app_name }}"
    dest=/usr/bin/{{ galaxie_mozilla_firefox_app_name }}
    state=link

- name: Creat /usr/share/applications/{{ galaxie_mozilla_firefox_app_name }}.desktop is ok
  template:
    src=templates/{{ galaxie_mozilla_firefox_app_name }}.desktop.j2
    dest=/usr/share/applications/{{ galaxie_mozilla_firefox_app_name }}.desktop
    backup=no