---
# add /var/qmail/man on MANDATORY_MANPATH
# /etc/manpath.config
# after MANDATORY_MANPATH           /usr/local/share/man

- name: add if {{ galaxie_qmail_server_qmail_dir }}/man on MANDATORY_MANPATH
  lineinfile:
    dest=/etc/manpath.config
    line="MANDATORY_MANPATH           {{ galaxie_qmail_server_qmail_dir }}/man"
    state=present
    regexp="^MANDATORY_MANPATH           /usr/local/share/man*"
    insertafter=yes