---
# qmail-send
- name: check if service {{ galaxie_qmail_server_service_send }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_send }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  when: galaxie_qmail_server_config_send

- name: add {{ galaxie_qmail_server_service_send }} service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: not command_result|success and galaxie_qmail_server_config_send

# qmail-smtpd ipv4
- name: check if service {{ galaxie_qmail_server_service_smtpd_ipv4 }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpd_ipv4 }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  when: galaxie_qmail_server_config_smtpd_ipv4

- name: add {{ galaxie_qmail_server_service_smtpd_ipv4 }} service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd_ipv4 }}
  when: not command_result|success and galaxie_qmail_server_config_smtpd_ipv4

# qmail-smtpsd ipv4
- name: check if service {{ galaxie_qmail_server_service_smtpsd_ipv4 }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpsd_ipv4 }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  when: galaxie_qmail_server_config_smtpsd_ipv4

- name: add {{ galaxie_qmail_server_service_smtpsd_ipv4 }} service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd_ipv4 }}
  when: not command_result|success and galaxie_qmail_server_config_smtpsd_ipv4

# qmail-smtpd ipv6
- name: check if service {{ galaxie_qmail_server_service_smtpd_ipv6 }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpd_ipv6 }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  when: galaxie_qmail_server_config_smtpd_ipv6

- name: add {{ galaxie_qmail_server_service_smtpd_ipv6 }} service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd_ipv6 }}
  when: not command_result|success and galaxie_qmail_server_config_smtpd_ipv6

# qmail-smtpsd ipv6
- name: check if service {{ galaxie_qmail_server_service_smtpsd_ipv6 }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpsd_ipv6 }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  when: galaxie_qmail_server_config_smtpsd_ipv6

- name: add qmail-smtpsd-ipv6 service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd_ipv6 }}
  when: not command_result|success and galaxie_qmail_server_config_smtpsd_ipv6