---
# Configure services to start
- name: creat "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}" service directories
  file:
    path="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}"
    state=directory
    owner=root
    group=root
    mode=1755
  tags: supervise

- name: set statup script "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/run"
  template:
    src=service-qmail-smtpsd-run.j2
    dest="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/run"
    mode=0700
  tags: supervise

# Configure multilog service
- name: creat "{{ galaxie_qmail_server_multilog_dir }}/{{ galaxie_qmail_server_service_smtpsd }}" multilog directory
  file:
    path="{{ galaxie_qmail_server_multilog_dir }}/{{ galaxie_qmail_server_service_smtpsd }}"
    owner="{{ galaxie_qmail_server_qmaill_user }}"
    group=root
    state=directory
    mode=2755
  tags: multilog

- name: creat "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/log" log directorie
  file:
    path="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/log"
    state=directory
    owner=root
    group=root
    mode=0755
  tags: supervise

- name: set statup script "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/log/run"
  template:
    src=service-qmail-smtpsd-log-run.j2
    dest="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}/log/run"
    mode=0700
  tags: supervise