---
# Configure service to start via Systemd
# https://github.com/aperezdc/perezdecastro.org/blob/master/stash/recipe-running-qmail-send-under-systemd.markdown
# http://mario.raval.li/2012/11/30/qmail-systemd/
# http://0pointer.de/blog/projects/inetd.html

- name: set statup script "/lib/systemd/system/qmail-smtpd.socket"
  template:
    src="qmail-smtpd.socket.j2"
    dest="/lib/systemd/system/qmail-smtpd.socket"
    mode=0644
  tags: qmail-smtpd-service

- name: set statup script "/lib/systemd/system/qmail-smtpd@.service"
  template:
    src="qmail-smtpd@.service.j2"
    dest="/lib/systemd/system/qmail-smtpd@.service"
    mode=0644
  tags: qmail-smtpd-service

- name: enable qmail-smtpd.socket
  service:
    name=qmail-smtpd.socket
    state=started
    enabled=yes
  tags: qmail-smtpd-service