---
# Configure service to start via Native Syetemd
# https://github.com/aperezdc/perezdecastro.org/blob/master/stash/recipe-running-qmail-send-under-systemd.markdown
# http://mario.raval.li/2012/11/30/qmail-systemd/

- name: set statup script "/lib/systemd/system/{{ galaxie_qmail_server_service_send }}.service"
  template:
    src="qmail-send.service.j2"
    dest="/lib/systemd/system/{{ galaxie_qmail_server_service_send }}.service"
    mode=0644
  tags: qmail-send-service

- name: check if service {{ galaxie_qmail_server_service_send }} is registered
  shell: "/usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_send }}"
  failed_when: "'update-service: fatal:' in command_result.stderr"
  changed_when: false
  register: command_result
  ignore_errors: yes
  tags: qmail-send-service

- name: remove {{ galaxie_qmail_server_service_send }} service
  shell: /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: command_result|success
  tags: qmail-send-service

- name: remove previous statup script for daemontools"
  file:
    state=absent
    path="{{ item }}"
  with_items:
    - "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}/log/run"
    - "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}/log"
    - "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}/run"
    - "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}"
    - "{{ galaxie_qmail_server_multilog_dir }}/{{ galaxie_qmail_server_service_send }}"
  tags: qmail-send-service

- name: enable {{ galaxie_qmail_server_service_send }}
  service:
    name={{ galaxie_qmail_server_service_send }}
    state=started
    enabled=yes
  tags: qmail-send-service