- name: remove other MTA services
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
    - exim4
    - exim4-daemon-light
    - postfix
    - sendmail
    - sendmail-base
    - sendmail-bin
    - sendmail-cf
  tags: mta

- name: get local fake MTA
  get_url:
    url=http://qmailrocks.thibs.com/downloads/deb-packages/mta-local_1.0_all.deb
    dest={{ galaxie_qmail_server_source_dir }}
  tags: mta

- name: install local mta-local_1.0_all.deb mta
  apt:
    deb={{ galaxie_qmail_server_source_dir }}/mta-local_1.0_all.deb
  changed_when: false
  tags: mta

- name: symlink to use qmail instead of default mta
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items:
    - { src: '{{ galaxie_qmail_server_qmail_dir }}/bin/sendmail', dest: '/usr/lib/sendmail' }
    - { src: '{{ galaxie_qmail_server_qmail_dir }}/bin/sendmail', dest: '/usr/sbin/sendmail' }
  tags: mta