---
- name: check packages for cdb building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
  tags: cdb

- name: check "{{ galaxie_qmail_server_source_dir }}" directory
  file:
    path="{{ galaxie_qmail_server_source_dir }}"
    owner=root
    group=root
    state=directory
    mode=0755
  tags: cdb

- name: get "{{ galaxie_qmail_server_cdb_source_url }}"
  get_url:
    url="{{ galaxie_qmail_server_cdb_source_url }}"
    dest={{ galaxie_qmail_server_source_dir }}
    sha256sum=1919577799a50c080a8a05a1cbfa5fa7e7abc823d8d7df2eeb181e624b7952c5
  register: galaxie_qmail_server_cdb_download
  tags: cdb

- name: delete "{{ galaxie_qmail_server_cdb_source_dir }}"
  file:
    path="{{ galaxie_qmail_server_cdb_source_dir }}"
    state=absent
  when: galaxie_qmail_server_cdb_download.changed
  tags: cdb

- name: Unarchive {{ galaxie_qmail_server_cdb_download.dest }}
  unarchive:
    src="{{ galaxie_qmail_server_cdb_download.dest }}"
    dest="{{ galaxie_qmail_server_source_dir }}"
    copy=no
  when: galaxie_qmail_server_cdb_download.changed
  tags: cdb

- name: fixe errno bug on "{{ galaxie_qmail_server_cdb_source_dir }}/error.h" file
  replace:
    dest="{{ galaxie_qmail_server_cdb_source_dir }}/error.h"
    regexp="^extern int errno;"
    replace="#include <errno.h>"
  tags: cdb

- name: check src/conf-dhfile
  lineinfile:
    dest="{{ galaxie_qmail_server_cdb_source_dir }}/error.h"
    line="#include <errno.h>"
    state=present
  tags: cdb

- name: build {{ galaxie_qmail_server_cdb_source_name }} on "{{ galaxie_qmail_server_cdb_source_dir }}" directory
  shell: make
    chdir="{{ galaxie_qmail_server_cdb_source_dir }}"
  changed_when: false
  tags: cdb

- name: install {{ galaxie_qmail_server_cdb_source_name }}
  shell: make setup check
    chdir="{{ galaxie_qmail_server_cdb_source_dir }}"
  changed_when: false
  tags: cdb
