---
# Info checking and notify relaunch of services
- name: check if service {{ galaxie_qmail_server_service_send }} is registered
  shell:
    /usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_send }}
  failed_when: "serviceSendRegistered.rc == 2"
  changed_when: "serviceSendRegistered.rc == 1"
  register:
    serviceSendRegistered
  ignore_errors:
    yes
  notify:
    - register qmail-send service
    - restart qmail-send service
  tags: install

- name: check if service {{ galaxie_qmail_server_service_smtpd }} is registered
  shell:
    /usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpd }}
  failed_when: "serviceSmtpRegistered.rc == 2"
  changed_when: "serviceSmtpRegistered.rc == 1"
  register:
    serviceSmtpRegistered
  ignore_errors:
    yes
  notify:
    - register qmail-smtpd service
    - restart qmail-smtpd service
  tags: install

- name: check if service {{ galaxie_qmail_server_service_smtpsd }} is registered
  shell:
    /usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpsd }}
  failed_when: "serviceSmtpRegistered.rc == 2"
  changed_when: "serviceSmtpRegistered.rc == 1"
  register:
    serviceSmtpRegistered
  ignore_errors:
    yes
  notify:
    - register qmail-smtpsd service
    - restart qmail-smtpsd service
  tags: install
# il en faut un


###############################################################################
#
# install - Building and installing
#

# Users and Groups creation
- name: create groups
  group:
    name={{ item }}
    state=present
    system=yes
  with_items:
    - "{{ galaxie_qmail_server_qmail_group }}"
    - "{{ galaxie_qmail_server_nofiles_group }}"
  tags: install

- name: create users
  user:
    name={{ item.username }}
    system=yes
    createhome=no
    home={{ galaxie_qmail_server_qmail_dir }}
    state=present
    group={{ item.group }}
  with_items:
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: qmaild }
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: qmaill }
    - { group: "{{ galaxie_qmail_server_nofiles_group }}", username: qmailp }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmailq }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmailr }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmails }
  tags: install

- name: create user '{{ galaxie_qmail_server_alias_user }}'
  user:
    name={{ galaxie_qmail_server_alias_user }}
    system=yes
    createhome=no
    home={{ galaxie_qmail_server_qmail_dir }}/alias
    state=present
    group="{{ galaxie_qmail_server_nofiles_group }}"
  tags: install

- name: check {{ galaxie_qmail_server_qmail_dir }}/alias directory
  file:
    path={{ galaxie_qmail_server_qmail_dir }}/alias
    state=directory
    owner={{ galaxie_qmail_server_alias_user }}
    group={{ galaxie_qmail_server_qmail_group }}
    mode=2755

# Installation
- name: packages for qmail building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - daemontools
    - daemontools-run
    - ucspi-tcp
    - passwd
    - libssl-dev
    - libperl-dev
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: check {{ galaxie_qmail_server_source_dir }} directory
  file:
    path={{ galaxie_qmail_server_source_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: get qmail sources
  get_url:
    url=http://cr.yp.to/software/qmail-1.03.tar.gz
    dest="{{ galaxie_qmail_server_source_dir }}"
    sha256sum=21ed6c562cbb55092a66197c35c8222b84115d1acab0854fdb1ad1f301626f88
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: get qmail patches
  get_url:
    url=http://qmail.jms1.net/patches/qmail-1.03-jms1-7.10.patch
    dest="{{ galaxie_qmail_server_source_dir }}"
    sha256sum=3807b4adfc7dbf83e3e2e9e0c841b3443e3bc468bc91ffd240dd420a7fcaa84b
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: empty build directory
  file:
    path={{ item }}
    state=absent
    force=yes
  with_items:
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03'
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10'
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: apply qmail patches
  shell: '{{ item }}'
  with_items:
    - tar xvzf {{ galaxie_qmail_server_source_dir }}/qmail-1.03.tar.gz -C {{ galaxie_qmail_server_source_dir }}
    - cd {{ galaxie_qmail_server_source_dir }}/qmail-1.03 && patch < {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10.patch
    - mv {{ galaxie_qmail_server_source_dir }}/qmail-1.03 {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: build qmail-1.03-jms1-7.10
  shell: make
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: install qmail manuel
  shell: make man
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: install qmail-1.03-jms1-7.10
  shell: make setup check
    chdir="{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10"
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

###############################################################################
#
# system - Preparing system for launch
#
- name: check supervise dir
  file:
    path={{ galaxie_qmail_server_supervise_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
  tags: system
