---
# Info checking and notify relaunch of services
- name: check if service {{ galaxie_qmail_server_service_send }} is registered
  shell:
    /usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_send }}
  failed_when: "serviceSendRegistered.rc == 2"
  changed_when: "serviceSendRegistered.rc == 1"
  register:
    serviceSendRegistered
  ignore_errors:
    yes
  notify:
    - register qmail-send service
    - restart qmail-send service

- name: check if service {{ galaxie_qmail_server_service_smtpd }} is registered
  shell:
    /usr/sbin/update-service --list | grep {{ galaxie_qmail_server_service_smtpd }}
  failed_when: "serviceSmtpRegistered.rc == 2"
  changed_when: "serviceSmtpRegistered.rc == 1"
  register:
    serviceSmtpRegistered
  ignore_errors:
    yes
  notify:
    - register qmail-smtp service
    - restart qmail-smtp service

# il en faut un


###############################################################################
#
# install - Building and installing
#
- name: create groups
  group:
    name={{ item }}
    state=present
    system=yes
  with_items:
    - qmail
    - nofiles
  tags: install

- name: create users
  user:
    name={{ item.username }}
    system=yes
    home={{ galaxie_qmail_server_qmail_dir }}
    state=present
    group={{ item.group }}
  with_items:
    - { group: nofiles, username: qmaild }
    - { group: nofiles, username: qmaill }
    - { group: nofiles, username: qmailp }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmailq }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmailr }
    - { group: "{{ galaxie_qmail_server_qmail_group }}", username: qmails }
  tags: install

- name: create user '{{ galaxie_qmail_server_alias_user }}'
  user:
    name={{ galaxie_qmail_server_alias_user }}
    system=yes
    createhome=no
    home={{ galaxie_qmail_server_qmail_dir }}/alias
    state=present
    group=nofiles
  tags: install

- name: check {{ galaxie_qmail_server_qmail_dir }}/alias directory
  file:
    path={{ galaxie_qmail_server_qmail_dir }}/alias
    state=directory
    owner={{ galaxie_qmail_server_alias_user }}
    group={{ galaxie_qmail_server_qmail_group }}
    mode=2755

- name: packages for qmail building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - daemontools
    - daemontools-run
    - ucspi-tcp
    - passwd
    - libssl-dev
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: check {{ galaxie_qmail_server_source_dir }} directory
  file:
    path={{ galaxie_qmail_server_source_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: get qmail sources
  get_url:
    url=http://cr.yp.to/software/qmail-1.03.tar.gz
    dest={{ galaxie_qmail_server_source_dir }}
    sha256sum=21ed6c562cbb55092a66197c35c8222b84115d1acab0854fdb1ad1f301626f88
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: get qmail patches
  get_url:
    url=http://qmail.jms1.net/patches/qmail-1.03-jms1-7.10.patch
    dest={{ galaxie_qmail_server_source_dir }}
    sha256sum=3807b4adfc7dbf83e3e2e9e0c841b3443e3bc468bc91ffd240dd420a7fcaa84b
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: empty build directory
  file:
    path={{ item }}
    state=absent
    force=yes
  with_items:
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03'
    - '{{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10'
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: apply qmail patches
  shell: '{{ item }}'
  with_items:
    - tar xvzf {{ galaxie_qmail_server_source_dir }}/qmail-1.03.tar.gz -C {{ galaxie_qmail_server_source_dir }}
    - cd {{ galaxie_qmail_server_source_dir }}/qmail-1.03 && patch < {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10.patch
    - mv {{ galaxie_qmail_server_source_dir }}/qmail-1.03 {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install

- name: build and install qmail
  shell: '{{ item }}'
  with_items:
    - cd {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10 && make
    - cd {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10 && make man
    - cd {{ galaxie_qmail_server_source_dir }}/qmail-1.03-jms1-7.10 && make setup check
  when: serviceSmtpRegistered|failed or serviceSendRegistered|failed
  tags: install


###############################################################################
#
# system - Preparing system for launch
#
- name: supervise dir
  file:
    path={{ galaxie_qmail_server_supervise_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
  tags: system

- name: create multilog directories
  file:
    path={{ galaxie_qmail_server_multilog_dir }}/{{ item }}
    owner={{ galaxie_qmail_server_qmaill_user }}
    group=root
    state=directory
    mode=2755
  with_items:
    - '{{ galaxie_qmail_server_service_send }}'
    - '{{ galaxie_qmail_server_service_smtpd }}'
  tags: system

- name: qmail-send & qmail-smtp service directories
  file:
    path={{ galaxie_qmail_server_supervise_dir }}/{{ item }}
    state=directory
    owner=root
    group=root
    mode=1755
  with_items:
    - '{{ galaxie_qmail_server_service_send }}'
    - '{{ galaxie_qmail_server_service_smtpd }}'
  tags: system

- name: remove duplicate services
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
    - exim4
    - exim4-daemon-light
    - postfix
    - sendmail
    - sendmail-base
    - sendmail-bin
    - sendmail-cf
  tags: system

- name: get local mta
  get_url:
    url=http://qmailrocks.thibs.com/downloads/deb-packages/mta-local_1.0_all.deb
    dest={{ galaxie_qmail_server_source_dir }}
  tags: system

- name: install local mta
  apt:
    deb={{ galaxie_qmail_server_source_dir }}/mta-local_1.0_all.deb
  tags: system

- name: symlink to use qmail instead of default mta
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items:
    - { src: '{{ galaxie_qmail_server_qmail_dir }}/bin/sendmail', dest: '/usr/lib/sendmail' }
    - { src: '{{ galaxie_qmail_server_qmail_dir }}/bin/sendmail', dest: '/usr/sbin/sendmail' }
  tags: system

- name: qmail-send & qmail-smtpd runnners
  template:
    src={{ item.tmpl }}
    dest={{ galaxie_qmail_server_supervise_dir }}/{{ item.service }}/run
    mode=0700
  with_items:
    - { service: '{{ galaxie_qmail_server_service_send }}', tmpl: 'service-qmail-send-run.j2' }
    - { service: '{{ galaxie_qmail_server_service_smtpd }}', tmpl: 'service-qmail-smtpd-run.j2' }
  tags: config

- name: send { galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/Makefile
  template:
    src=service-qmail-smtpd-makefile.j2
    dest={{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/Makefile
    mode=0644
    owner=root
    group=root
  tags: config

- name: send "{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}"/tcp
  template:
    src=service-qmail-smtpd-tcpdb.j2
    dest={{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/tcp
    mode=0644
    owner=root
    group=root
  notify: rebuild qmail-smtpd tcpdb
  tags: config

- name: check {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/Makefile
  template:
    src=service-qmail-smtpd-makefile.j2
    dest={{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/Makefile
    mode=0644
    owner=root
    group=root
  tags: config

- name: creat {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/tcp.cdb
  shell: make
    chdir={{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}/

- name: qmail-send & qmail-smtpd service log directories
  file:
    path={{ galaxie_qmail_server_supervise_dir }}/{{ item }}/log
    state=directory
    owner=root
    group=root
    mode=0755
  with_items:
    - '{{ galaxie_qmail_server_service_send }}'
    - '{{ galaxie_qmail_server_service_smtpd }}'
  tags: config

- name: qmail-send & qmail-smtpd service log runners
  template:
    src=service-any-log-run.j2
    dest={{ galaxie_qmail_server_supervise_dir }}/{{ item.service }}/log/run
    mode=0700
  with_items:
    - { service: '{{ galaxie_qmail_server_service_send }}', log_dest: '{{ galaxie_qmail_server_multilog_dir }}/{{ galaxie_qmail_server_service_send }}'}
    - { service: '{{ galaxie_qmail_server_service_smtpd }}', log_dest: '{{ galaxie_qmail_server_multilog_dir }}/{{ galaxie_qmail_server_service_smtpd }}' }
  tags: config

# Fine grained configuration
- include: config.yml
