---

- name: Check if {{ galaxie_common_primary_local }} locale present
  tags: locales
  locale_gen:
    name={{ item }}
    state=present
  with_items:
    - "{{ galaxie_common_primary_local }}"
    - "{{ galaxie_common_secondary_local }}"
  register: locale_gen_status

- name: Update and Set locale
  tags: locales
  command: /usr/sbin/update-locale LANG={{ galaxie_common_primary_local }} LANGUAGE={{ galaxie_common_language }}
  when: locale_gen_status.changed and ansible_os_family == "Debian"

- name: Set timezone area {{ galaxie_common_tzdata_areas }}
  tags: locales
  debconf:
    name=tzdata
    question='tzdata/Areas'
    value='{{ galaxie_common_tzdata_areas }}'
    vtype='select'
  when: ansible_os_family == "Debian"
  notify:
    - update timezone

- name: Set {{ galaxie_common_tzdata_areas }}/{{ galaxie_common_tzdata_zones }} to /etc/timezone file
  tags: locales
  template:
    src=timezone.j2
    dest=/etc/timezone
  notify:
    - update timezone

- name: Set timezone
  tags: locales
  debconf:
    name=tzdata
    question='tzdata/Zones/{{ galaxie_common_tzdata_areas }}'
    value='{{ galaxie_common_tzdata_zones }}'
    vtype='select'
  when: ansible_os_family == "Debian"
  notify:
    - update timezone

- name: desired manpages are present
  tags: locales
  apt: pkg="{{item}}" state=present
  with_items:
    - manpages-fr
    - manpages-fr-extra
  when: galaxie_common_language == "fr" and ansible_os_family == "Debian"
