---
# qmail-send
- name: register qmail-send service
  shell:
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: serviceSendRegistered|failed

- name: restart qmail-send service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }} &&
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: serviceSendRegistered|success

# qmail-smtpd-ipv4
- name: add qmail-smtpd-ipv4service
  shell: /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}

- name: remove qmail-smtpd-ipv4 service
  shell: /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}

- name: restart qmail-smtpd-ipv4 service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }} &&
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}

- name: rebuild qmail-smtpd-ipv4 tcpdb
  shell:
    make
    chdir="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}"
  notify:
    - restart qmail-smtpd-ipv4 service

# qmail-smtpsd
- name: register qmail-smtpsd service
  shell:
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}
  when: serviceSmtpRegistered|failed

- name: restart qmail-smtpsd service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }} &&
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}
  when: serviceSmtpRegistered|success

- name: rebuild qmail-smtpsd tcpdb
  shell:
    make
    chdir="{{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpsd }}"
  notify:
    - register qmail-smtpsd service
    - restart qmail-smtpsd service