---

- name: register qmail-send service
  shell:
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: serviceSendRegistered|failed

- name: restart qmail-send service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }} &&
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_send }}
  when: serviceSendRegistered|success

- name: register qmail-smtp service
  shell:
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}
  when: serviceSmtpRegistered|failed

- name: restart qmail-smtp service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }} &&
    /usr/sbin/update-service --add {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }}
  when: serviceSmtpRegistered|success

- name: rebuild qmail-smtpd tcpdb
  shell:
    cd {{ galaxie_qmail_server_supervise_dir }}/{{ galaxie_qmail_server_service_smtpd }} && make
  notify:
    - register qmail-smtp service
    - restart qmail-smtp service