- hosts: galaxie_pvr
  sudo: true

  vars:
    build_dir: /usr/src/galaxie_tvheadend_build_
    git_src: https://github.com/tvheadend/tvheadend.git

  tasks:
   - name: Update Apt
     apt: update_cache=yes cache_valid_time=3600
   - name: Install required software
     action: apt pkg={{item}} state=installed
     with_items:
      - debhelper
      - pkg-config
      - libavahi-client-dev
      - libssl-dev
      - zlib1g-dev
      - wget
      - bzip2
      - libcurl4-gnutls-dev
      - git-core
      - liburiparser-dev
      - libavahi-client3
      - zlib1g
      - liburiparser1
      - xmltv-util

   - action: shell date '+%F'
     register: mydate
 
   - name: Delete previous installation
     file: path={{ build_dir  }}{{ mydate.stdout }} state=absent

   - name: Creates directory {{ build_dir  }}{{ mydate.stdout }}
     action: file dest={{ build_dir  }}{{ mydate.stdout }}  state=directory

   - name: Download Git master of TVHeadend
     shell: chdir={{ build_dir  }}{{ mydate.stdout }} git clone {{ git_src  }}
   
   - name: Building ...
     shell: chdir={{ build_dir  }}{{ mydate.stdout }}/tvheadend ./Autobuild.sh

   - action: shell ls {{ build_dir  }}{{ mydate.stdout }}/tvheadend_*.deb
     register: package_path

   - name: Install Package
     apt: deb={{ package_path.stdout }}

   - name: Copy init file
     shell: chdir={{ build_dir  }}{{ mydate.stdout }}/tvheadend/debian cp tvheadend.init /etc/init.d/tvheadend

   - name: Change permission of init file
     shell: chmod 755 /etc/init.d/tvheadend
     notify: restart tvheadend

  handlers:
   - name: restart tvheadend
     service: name=tvheadend state=restarted
