---

- name: activate debian jessie main contrib non-free repository
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb http://ftp.fr.debian.org/debian/ jessie main non-free contrib"
    - "deb-src http://ftp.fr.debian.org/debian/ jessie main non-free contrib"
    - "deb http://security.debian.org/ jessie/updates main non-free contrib"
    - "deb-src http://security.debian.org/ jessie/updates main non-free contrib"
    - "deb http://ftp.fr.debian.org/debian/ jessie-updates main non-free contrib"
    - "deb-src http://ftp.fr.debian.org/debian/ jessie-updates main non-free contrib"

- name: update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install MySQL
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb
  notify:
    - restart mysql

- name: ensure mysql is running and starts on boot
  service:
    name=mysql
    state=started
    enabled=true

- name: copy .my.cnf file with root password credentials
  template:
    src=my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: Setup MySQL root password
  mysql_user:
    name=root
    password={{ galaxie.mysql.root_db_password }}
    host={{ item }}
    state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: ensure anonymous users are not in the database
  mysql_user:
    name=''
    host={{ item }}
    state=absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: remove the test database
  mysql_db:
    name=test
    state=absent

