---

- name: Install Apache
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - apache2-utils
    - apache2-mpm-prefork
  notify:
    - restart apache

- name: Add "{{ galaxie_ansible_user }}" user in www-data group
  user:
    name: "{{ galaxie_ansible_user }}"
    groups: "www-data"
    append: yes

- include: php.yml