---

- name: Install Apache
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - apache2-utils
  notify:
    - restart apache

#- name: Add "{{ galaxie.user }}" user in www-data group
#  user:
#    name: "{{ galaxie.user }}"
#    groups: "www-data"
#    append: yes

- include: php.yml