---
# Common and path
glx_slashpackage_dir: "/package"
galaxie_qmail_server_multilog_user: "multilog"
galaxie_qmail_server_multilog_dir: "/var/multilog"
galaxie_qmail_server_qmaild_user: "qmaild"
galaxie_qmail_server_qmaill_user: "qmaill"
galaxie_qmail_server_qmailp_user: "qmailp"
galaxie_qmail_server_qmailq_user: "qmailq"
galaxie_qmail_server_qmailr_user: "qmailr"
galaxie_qmail_server_qmails_user: "qmails"
galaxie_qmail_server_qmail_group: "qmail"
galaxie_qmail_server_nofiles_group: "nofiles"
galaxie_qmail_server_alias_user: "alias"
galaxie_qmail_server_service_name: "qmail"
galaxie_qmail_server_service_send: "qmail-send"
galaxie_qmail_server_service_smtpd_ipv4: "qmail-smtpd-ipv4"
galaxie_qmail_server_service_smtpd_ipv6: "qmail-smtpd-ipv6"
galaxie_qmail_server_service_smtpsd_ipv4: "qmail-smtpsd-ipv4"
galaxie_qmail_server_service_smtpsd_ipv6: "qmail-smtpsd-ipv6"
galaxie_qmail_server_service_ipv4: "{{ ansible_default_ipv4.address }}"
galaxie_qmail_server_service_ipv6: "{{ ansible_all_ipv6_addresses[0] }}"
galaxie_qmail_server_service_ipv6_interface: "eth0"

galaxie_qmail_server_qmail_dir: "/var/qmail"
glx_supervise_dir: "/var/lib/supervise"

# qmail-scanner
galaxie_qmail_server_qmail_scanner_user: "clamav"

# simscan
galaxie_qmail_server_simscan_user: "simscan"
galaxie_qmail_server_simscan_group: "simscan"

# Special

# via systemd
galaxie_qmail_server_config_send: true
galaxie_qmail_server_config_smtpd: true

# via dameon tools
galaxie_qmail_server_config_smtpd_ipv4: true
galaxie_qmail_server_config_smtpd_ipv6: false
galaxie_qmail_server_config_smtpsd_ipv4: true
galaxie_qmail_server_config_smtpsd_ipv6: false

# special - antispam
galaxie_qmail_server_config_qmail_scanner: false
galaxie_qmail_server_config_simscan: false
# special - smtproutes
galaxie_qmail_server_set_smtproutes: false
galaxie_qmail_server_control_smtproutes: ""
# special - virtualdomains
galaxie_qmail_server_set_virtualdomains: false
galaxie_qmail_server_control_virtualdomains: ""
# special - scripts
galaxie_qmail_server_install_qmailctl: true
galaxie_qmail_server_install_qfixpermissions: true

# Control
galaxie_qmail_server_domain: "galaxie.ici"
galaxie_qmail_server_control_me: "{{ ansible_hostname }}.{{ galaxie_qmail_server_domain }}"
galaxie_qmail_server_control_defaultdomain: "{{ galaxie_qmail_server_domain }}"
galaxie_qmail_server_control_plusdomain: "{{ galaxie_qmail_server_domain }}"

galaxie_qmail_server_control_locals:
  - "localhost"
  - "localhost.localdomain"
  - "{{ ansible_hostname }}"
  - "{{ ansible_hostname }}.{{ galaxie_qmail_server_domain }}"
  - "{{ galaxie_qmail_server_domain }}"
galaxie_qmail_server_control_rcpthosts:
  - "{{ galaxie_qmail_server_domain }}"


galaxie_qmail_server_control_defaultdelivery: "./Maildir/"
galaxie_qmail_server_control_concurrencyremote: "255"
galaxie_qmail_server_control_concurrencyincoming: "30"
galaxie_qmail_server_control_spfbehavior: "3"
galaxie_qmail_server_control_bouncefrom: "postmaster"
galaxie_qmail_server_control_doublebouncehost: "{{ galaxie_qmail_server_domain }}"
galaxie_qmail_server_control_doublebounceto: "postmaster"
galaxie_qmail_server_control_databytes: "8000000"
galaxie_qmail_server_control_timeoutsmtpd: "30"

# cdb
galaxie_qmail_server_cdb_source_repository: "http://cr.yp.to/cdb"
galaxie_qmail_server_cdb_source_name: "cdb-0.75"
galaxie_qmail_server_cdb_source_extension: "tar.gz"
galaxie_qmail_server_cdb_source_url: "{{ galaxie_qmail_server_cdb_source_repository }}/{{ galaxie_qmail_server_cdb_source_name }}.{{ galaxie_qmail_server_cdb_source_extension }}"
galaxie_qmail_server_cdb_source_dir: "{{ galaxie_qmail_server_source_dir }}/cdb-0.75"

# ucspi-tcp6
glx_ucspi_tcp6_force_install: true
glx_ucspi_tcp6_source_repository: "http://www.fehcom.de/ipnet/ucspi-tcp6"
glx_ucspi_tcp6_source_name: "ucspi-tcp6-1.00a"
glx_ucspi_tcp6_source_extension: "tgz"
glx_ucspi_tcp6_source_url: "{{ glx_ucspi_tcp6_source_repository }}/{{ glx_ucspi_tcp6_source_name }}.{{ glx_ucspi_tcp6_source_extension }}"
glx_ucspi_tcp6_source_dir: "/usr/src"

# ucspi-ssl
glx_ucspi_ssl_force_install: true
glx_ucspi_ssl_certificates_dir: "/etc/ssl/certs"
glx_ucspi_ssl_dh_parameter_file: "{{ glx_ucspi_ssl_certificates_dir }}/dhparam.pem"
glx_ucspi_ssl_dh_bits: "2048"
glx_ucspi_ssl_source_repository: "http://www.fehcom.de/ipnet/ucspi-ssl"
glx_ucspi_ssl_source_name: "ucspi-ssl-0.95b"
glx_ucspi_ssl_source_extension: "tgz"
glx_ucspi_ssl_source_url: "{{ glx_ucspi_ssl_source_repository }}/{{ glx_ucspi_ssl_source_name }}.{{ glx_ucspi_ssl_source_extension }}"
glx_ucspi_ssl_source_dir: "/usr/src"
# ./src/conf-cadir
glx_ucspi_ssl_conf_cadir: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-cadir"
# ./src/conf-cafile
glx_ucspi_ssl_conf_cafile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-cafile"
# ./src/conf-cc
glx_ucspi_ssl_conf_cc: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-cc"
# ./src/conf-ccafile
glx_ucspi_ssl_conf_ccafile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ccafile"
# ./src/conf-ccperl
glx_ucspi_ssl_conf_ccperl: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ccperl"
# ./src/conf-certchainfile
glx_ucspi_ssl_conf_certchainfile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-certchainfile"
# ./src/conf-certfile
glx_ucspi_ssl_conf_certfile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-certfile"
# ./src/conf-ciphers
glx_ucspi_ssl_conf_ciphers: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ciphers"
# ./src/conf-dhfile
glx_ucspi_ssl_conf_dhfile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-dhfile"
# ./src/conf-dl
glx_ucspi_ssl_conf_dl: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-dl"
# ./src/conf-keyfile
glx_ucspi_ssl_conf_keyfile: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-keyfile"
# ./src/conf-ld
glx_ucspi_ssl_conf_ld: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ld"
# ./src/conf-ldperl
glx_ucspi_ssl_conf_ldperl: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ldperl"
# ./src/conf-perl
glx_ucspi_ssl_conf_perl: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-perl"
# ./src/conf-rsa
glx_ucspi_ssl_conf_rsa: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-rsa"
# ./src/conf-ssl
glx_ucspi_ssl_conf_ssl: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ssl"
# ./src/conf-ssllib
glx_ucspi_ssl_conf_ssllib: "{{ glx_slashpackage_dir }}/host/superscript.com/net/{{ glx_ucspi_ssl_source_name }}/src/conf-ssllib"
# ./src/conf-tcpbin
# default /usr/local/bin
# This is the ucspi-tcp bin directory.  The ucspi-tcp executables should appear in it.
glx_ucspi_ssl_conf_tcpbin: "{{ glx_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b/src/conf-tcpbin


# s/qmail
glx_s_qmail_force_install: true
glx_s_qmail_source_repository: "http://fehcom.de/sqmail"
glx_s_qmail_source_name: "sqmail-3.0.2"
glx_s_qmail_source_extension: "tgz"
glx_s_qmail_source_url: "{{ glx_s_qmail_source_repository }}/{{ glx_s_qmail_source_name }}.{{ glx_s_qmail_source_extension }}"
glx_s_qmail_source_dir: "/usr/src"

# certificate
galaxie_qmail_server_openssl_key_gen: false
galaxie_qmail_server_openssl_key_bit: "2048"
galaxie_qmail_server_openssl_key_days: "3650"
galaxie_qmail_server_openssl_cert_C: "FR"
galaxie_qmail_server_openssl_cert_ST: "Ile-de-France"
galaxie_qmail_server_openssl_cert_L: "Paris"
galaxie_qmail_server_openssl_cert_O: "Galaxie"
galaxie_qmail_server_openssl_cert_OU: "IT"
galaxie_qmail_server_openssl_cert_CN: "{{ ansible_hostname }}.{{ galaxie_qmail_server_domain }}"
galaxie_qmail_server_openssl_subj: "/C={{ galaxie_qmail_server_openssl_cert_C }}/ST={{ galaxie_qmail_server_openssl_cert_ST }}/L={{ galaxie_qmail_server_openssl_cert_L }}/O={{ galaxie_qmail_server_openssl_cert_O }}/OU={{ galaxie_qmail_server_openssl_cert_OU }}/CN={{ galaxie_qmail_server_openssl_cert_CN }}"

# Alias creation
# http://www.qmail.org/man/man5/dot-qmail.html
galaxie_qmail_server_alias_admins_list:
  - name: "root"
    value:
      - "root@{{ galaxie_qmail_server_domain }}"
  - name: "postmaster"
    value:
      - "root@{{ galaxie_qmail_server_domain }}"
  - name: "mailer-daemon"
    value:
      - "root@{{ galaxie_qmail_server_domain }}"
      
galaxie_qmail_server_alias_users_list:
  - name: "lulu"
    value:
      - "lulu@galaxie.ici"
  - name: "boris"
    value:
      - "boris@galaxie.ici"
      - "lulu@galaxie.ici"

