# Sorry Debian Team's
# Iceweasel is dependency of Gnome ! good joke guy's ! but no thanks !
# Remove deprecated Evolution the  Mail Client
- name: Remove mess from Debian it think Iceweasel is dependency of Gnome...
  apt:
    pkg={{ item }}
    purge=yes
    state=absent
    install_recommends=no
  with_items:
    - evolution
    - evolution-common
    - evolution-data-server
    - evolution-data-server-common
    - evolution-data-server-dbg
    - evolution-data-server-dev
    - evolution-dbg
    - evolution-dev
    - iceweasel
    - iceweasel-dbg
    - iceweasel-dev
    - iceweasel-downthemall
    - icedove
    - icedove-bidiui
    - icedove-dbg
    - icedove-dev


- name: Install Gnome Minimal without everydependency
  apt:
    pkg={{ item }}
    state=latest
    install_recommends=no
  with_items:
    - gnome-shell
    - gnome-shell-common
    - gnome-shell-extensions
    - gnome-session
    - gnome-terminal
    - gedit
    - gedit-plugins
    - nautilus
    - rabbitvcs-nautilus
    - gnome-control-center
    - gdm3
    - evince
    - gnome-menus
    - seahorse
    - gnome-themes-standard
    - adwaita-icon-theme
    - gnome-tweak-tool
    - gtk2-engines-pixbuf
    - shotwell
