---
galaxie_mozilla_thunderbird_prefix_dir: "/var/lib/galaxie"
galaxie_mozilla_thunderbird_cache_dir: "{{ galaxie_mozilla_thunderbird_prefix_dir }}/src"
galaxie_mozilla_thunderbird_opt_dir: "/opt"
galaxie_mozilla_thunderbird_os: "linux64"
galaxie_mozilla_thunderbird_lang: "fr"
galaxie_mozilla_thunderbird_app_name: "thunderbird"
galaxie_mozilla_thunderbird_downloader_url: "https://download.mozilla.org/?product={{ galaxie_mozilla_thunderbird_app_name }}-latest&os={{ galaxie_mozilla_thunderbird_os }}&lang={{ galaxie_mozilla_thunderbird_lang }}"
