---

- name: Check directorys
  file:
    path="{{item}}"
    owner=root
    group=root
    state=directory
    mode=0755
  with_items:
    - "{{ galaxie_mozilla_thunderbird_cache_dir }}"
    - "{{ galaxie_mozilla_thunderbird_opt_dir }}"

- name: Check for last version
  script: get_basename_by_url.sh '{{ galaxie_mozilla_thunderbird_downloader_url }}'
  register: galaxie_thunderbird_filename
  failed_when: not galaxie_thunderbird_filename.stdout
  changed_when: False

#- debug: msg="{{ galaxie_thunderbird_filename.stdout_lines[0] }}"

- name: Download {{ galaxie_thunderbird_filename.stdout_lines[0] }}
  get_url:
    url="{{ galaxie_mozilla_thunderbird_downloader_url }}"
    dest="{{ galaxie_mozilla_thunderbird_cache_dir }}/{{ galaxie_thunderbird_filename.stdout_lines[0] }}"
  when: galaxie_mozilla_thunderbird_downloader_url and galaxie_thunderbird_filename
  register: galaxie_thunderbird_download_status
  failed_when: not galaxie_mozilla_thunderbird_downloader_url

#- debug: msg="{{ galaxie_thunderbird_download_status }}"

- name: Delete {{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}
  file:
    path={{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}
    state=absent
  when: galaxie_thunderbird_download_status.changed

- name: Unarchive {{ galaxie_thunderbird_download_status.dest }}
  unarchive:
    src="{{ galaxie_thunderbird_download_status.dest }}"
    dest="{{ galaxie_mozilla_thunderbird_opt_dir }}"
    copy=no
  when: galaxie_thunderbird_download_status.changed

- name: Set permissions of {{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}
  file:
    path={{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}
    owner=root
    group=root
    state=directory
    mode=0755

- name: Set permissions of {{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}/
  file:
    path={{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}
    owner=root
    group=root
    recurse=yes

- name: Check symbolic link /usr/bin/{{ galaxie_mozilla_thunderbird_app_name }}
  file:
    src="{{ galaxie_mozilla_thunderbird_opt_dir }}/{{ galaxie_mozilla_thunderbird_app_name }}/{{ galaxie_mozilla_thunderbird_app_name }}"
    dest=/usr/bin/{{ galaxie_mozilla_thunderbird_app_name }}
    state=link

- name: Check /usr/share/applications/{{ galaxie_mozilla_thunderbird_app_name }}.desktop file
  template:
    src={{ galaxie_mozilla_thunderbird_app_name }}.desktop.j2
    dest=/usr/share/applications/{{ galaxie_mozilla_thunderbird_app_name }}.desktop
    backup=no