---
- name: Prepares target hosts to Galaxie's playbooks
  hosts: galaxie
  sudo: yes

  vars_files:
    - "galaxie-0-vars.yml"

  tasks:
    - name: "Setup | Is key locally present"
      when: newKey is defined
      stat:
        path="{{newKey}}"
      register: localKey
      delegate_to: localhost
      sudo: no

    - name: "Setup | key generation"
      command: "ssh-keygen -t rsa -b 2048 -f {{newKey}}"
      when: newKey is defined and not localKey.stat.exists
      delegate_to: localhost
      sudo: no

    - name: Setup | zoe group
      group:
        name="{{ ansibleUser }}"
        gid=4200
        state=present

    - name: Setup | zoe user
      user:
        name="{{ ansibleUser }}"
        uid=4200
        groups="{{ ansibleUser }},sudo"
        generate_ssh_key=yes
        state=present

    - name: Setup | access key upload
      authorized_key:
        user="{{ ansibleUser }}"
        key="{{ lookup('file', newKey+'.pub') }}"


    - name: validate sudoers
      lineinfile: "dest=/etc/sudoers state='present' regexp='^zoe' line='zoe ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s' "
      tags: reg


