---

- name: register service
  shell:
    /usr/sbin/update-service --add {{ galaxie_dnscache_server_supervise_dir }}/{{ galaxie_dnscache_server_service_name }}
  when: serviceRegistered|failed

- name: restart service
  shell:
    /usr/sbin/update-service --remove {{ galaxie_dnscache_server_supervise_dir }}/{{ galaxie_dnscache_server_service_name }} &&
    /usr/sbin/update-service --add {{ galaxie_dnscache_server_supervise_dir }}/{{ galaxie_dnscache_server_service_name }}
  when: serviceRegistered|success