#!/bin/sh
#
# pfix
# John Simpson <jms1@jms1.net> 2003-04-01
#
# fix permissions on perl library directories
#
# 2005-04-09 jms1 - changed copyright notice to indicate my intention
#   that this code is licensed under GPL version 2 only, rather than
#   GPL version 2 "or later".
#
###############################################################################
#
# Copyright (C) 2003-2005 John Simpson.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/licenses/gpl.txt
#
###############################################################################

LIST=`perl -e 'print join(" ",grep(/^[^\.]/,grep -d,@INC))'`

chown -R 0.0    $LIST
chmod -R go=u-w $LIST