#!/bin/bash
#Variable declaration
SRC_DIR=/usr/src
BUILD_DIR=$SRC_DIR/djbdns
SUPERVISE_DIR=/var/lib/supervise
SERVICE_DIR=/etc/service
MULTILOG_DIR=/var/multilog
DNSCACHE_UNAME=dnscache
TINYDNS_UNAME=tinydns
DNSLOG_UNAME=dnslog
DATE=`date +%Y%m%d%H%M%S`
SERVICE_IP=127.0.0.1
SERVICE_NAME=dnscache
#Check and Creat /var/src/dbdns directory
if [[ -e $BUILD_DIR ]]; then
    rm -rf $BUILD_DIR
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR
else
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR
fi
#Install the necessary
apt-get update && \
apt-get install build-essential daemontools daemontools-run ucspi-tcp && \
#If you apt conf file have deb-src http://ftp.fr.debian.org/debian/ sid main contrib non-free
apt-get source dbndns
#Build djbdns
if [[ -e $BUILD_DIR/djbdns-1.05 ]]; then
    cd $BUILD_DIR/djbdns-1.05
    dpkg-buildpackage -b
    cd $BUILD_DIR
fi
#Install the package
dpkg -i $BUILD_DIR/djbdns_1.05-8_*.deb
#Check and Creat Users dnscache, tinydns ,dnslog
for USER in {"$DNSCACHE_UNAME","$TINYDNS_UNAME","$DNSLOG_UNAME"}; do
    getent passwd $USER > /dev/null 2&>1
    if [ $? -ne 0 ]; then
        useradd -M -r -d /no/existant -s /no/existant $USER
    fi
done
#Check and Creat necessary directory
for DIR in {"$SUPERVISE_DIR","$SERVICE_DIR","$MULTILOG_DIR"}; do 
    if [[ ! -e $DIR ]]; then
        mkdir -p $DIR
    fi
done
#Configure dnscache
if [[ `update-service --list | grep -c $SERVICE_NAME` -eq 1 ]]; then
    update-service --remove $SUPERVISE_DIR/$SERVICE_NAME
fi
#dnscache-conf need root dns list inside dnsroots.global file 
if [[ ! -e /etc/dnsroots.global ]]; then
    echo '198.41.0.4'     >  /etc/dnsroots.global
    echo '192.228.79.201' >> /etc/dnsroots.global
    echo '192.33.4.12'    >> /etc/dnsroots.global
    echo '199.7.91.13'    >> /etc/dnsroots.global
    echo '192.203.230.10' >> /etc/dnsroots.global
    echo '192.5.5.241'    >> /etc/dnsroots.global
    echo '192.112.36.4'   >> /etc/dnsroots.global
    echo '128.63.2.53'    >> /etc/dnsroots.global
    echo '192.36.148.17'  >> /etc/dnsroots.global
    echo '192.58.128.30'  >> /etc/dnsroots.global
    echo '193.0.14.129'   >> /etc/dnsroots.global
    echo '199.7.83.42'    >> /etc/dnsroots.global
    echo '202.12.27.33'   >> /etc/dnsroots.global
fi
if [[ -e $SUPERVISE_DIR/$SERVICE_NAME ]]; then
    echo "mv $SUPERVISE_DIR/$SERVICE_NAME $SUPERVISE_DIR/$SERVICE_NAME.$DATE"
    mv $SUPERVISE_DIR/$SERVICE_NAME $SUPERVISE_DIR/$SERVICE_NAME.$DATE
fi
echo "dnscache-conf $DNSCACHE_UNAME $DNSLOG_UNAME $SUPERVISE_DIR/$SERVICE_NAME $SERVICE_IP"
dnscache-conf $DNSCACHE_UNAME $DNSLOG_UNAME $SUPERVISE_DIR/$SERVICE_NAME $SERVICE_IP
#Dnscache log management
#Creat $MULTILOG_DIR/$SERVICE_NAME outside /etc normaly /var/multilog
if [[ ! -e $MULTILOG_DIR/$SERVICE_NAME ]]; then
    mkdir -p $MULTILOG_DIR/$SERVICE_NAME
    chown $DNSLOG_UNAME:$DNSLOG_UNAME $MULTILOG_DIR/$SERVICE_NAME
    chmod 755 $MULTILOG_DIR/$SERVICE_NAME
    chmod g+s $MULTILOG_DIR/$SERVICE_NAME
else
    echo "mv $MULTILOG_DIR/$SERVICE_NAME $MULTILOG_DIR/$SERVICE_NAME.$DATE"
    mv $MULTILOG_DIR/$SERVICE_NAME $MULTILOG_DIR/$SERVICE_NAME.$DATE
    mkdir -p $MULTILOG_DIR/$SERVICE_NAME
    chown $DNSLOG_UNAME:$DNSLOG_UNAME $MULTILOG_DIR/$SERVICE_NAME
    chmod 755 $MULTILOG_DIR/$SERVICE_NAME
    chmod g+s $MULTILOG_DIR/$SERVICE_NAME
fi
#Modify $SUPERVISE_DIR/$SERVICE_NAME/log/run script for use $MULTILOG_DIR/$SERVICE_NAME directory
if [[ -e $SUPERVISE_DIR/$SERVICE_NAME/log/run ]]; then
    mv $SUPERVISE_DIR/$SERVICE_NAME/log/run $SUPERVISE_DIR/$SERVICE_NAME/log/run.old
    sed "s|./main|$MULTILOG_DIR/$SERVICE_NAME|g" $SUPERVISE_DIR/$SERVICE_NAME/log/run.old > $SUPERVISE_DIR/$SERVICE_NAME/log/run
    rm $SUPERVISE_DIR/$SERVICE_NAME/log/run.old
    chmod 755 $SUPERVISE_DIR/$SERVICE_NAME/log/run
    if [[ -e $SUPERVISE_DIR/$SERVICE_NAME/log/main ]]; then
        rm -rf $SUPERVISE_DIR/$SERVICE_NAME/log/main
    fi
fi
#Dnscache service management
if [[ `update-service --list | grep -c $SERVICE_NAME` -eq 0 ]]; then
    update-service --add $SUPERVISE_DIR/$SERVICE_NAME
else
    update-service --remove $SUPERVISE_DIR/$SERVICE_NAME
    update-service --add $SUPERVISE_DIR/$SERVICE_NAME
fi
#Modify /etc/resolv.conf
if [[ -e /etc/resolv.conf ]]; then
    echo "mv /etc/resolv.conf /etc/resolv.conf.$DATE"
    mv /etc/resolv.conf /etc/resolv.conf.$DATE
    echo '# Generated by galaxie_djbdns.sh' > /etc/resolv.conf
    echo 'nameserver 127.0.0.1' >> /etc/resolv.conf
else
    echo '# Generated by galaxie_djbdns.sh' > /etc/resolv.conf
    echo 'nameserver 127.0.0.1' >> /etc/resolv.conf
fi
