---
- name: Add emby.media Debian 7 key
  apt_key:
    url=http://download.opensuse.org/repositories/home:emby/Debian_7.0/Release.key
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- name: Add emby.media Debian 8 key
  apt_key:
    url=http://download.opensuse.org/repositories/home:emby/Debian_8.0/Release.key
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: activate Debian 7 emby-media repository
  apt_repository:
    repo="deb http://download.opensuse.org/repositories/home:/emby/Debian_7.0/ /"
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- name: activate Debian 8 emby-media repository
  apt_repository:
    repo="deb http://download.opensuse.org/repositories/home:/emby/Debian_8.0/ /"
    state=present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: update apt cache
  apt: update_cache=yes

- name: check dependency packages are present
  apt:
    pkg="{{item}}"
    state=installed
  with_items:
    - mono-runtime
    - mediainfo
    - libsqlite3-dev
    - imagemagick-6.q8
    - libmagickwand-6.q8-2
    - libmagickcore-6.q8-2

- name: check emby-server packages are present
  apt:
    pkg=emby-server
    state=installed
  register: emby_check

- name: start emby
  shell:
    service emby-server start
  when: emby_check.changed

- name: Check hostname by IP
  shell: dnsname {{ ansible_default_ipv4.address }}
  failed_when: "'fatal:' in hostnamebyip.stderr"
  changed_when: False
  register: hostnamebyip

- name: Next step
  debug: msg="Connect to http://{{ hostnamebyip.stdout }}:8096/web/wizardstart.html or http://{{ ansible_default_ipv4.address }}:8096/web/wizardstart.html"
  when: hostnamebyip.stdout
