---
- name: install "{{ galaxie_qmail_server_qmail_dir }}/bin/qmailctl" script
  template:
    src=qmailctl.j2
    dest={{ galaxie_qmail_server_qmail_dir }}/bin/qmailctl
    mode=0750
    owner=root
    group="{{ galaxie_qmail_server_qmail_group }}"
  when: galaxie_qmail_server_install_qmailctl
  tags: qmailctl

- name: delete "{{ galaxie_qmail_server_qmail_dir }}/bin/qmailctl"
  file:
    path="{{ galaxie_qmail_server_qmail_dir }}/bin/qmailctl"
    state=absent
  when: not galaxie_qmail_server_install_qmailctl
  tags: qmailctl

- name: creat symbolic link
  file:
    src="{{ galaxie_qmail_server_qmail_dir }}/bin/qmailctl"
    dest="/usr/local/bin/qmailctl"
    state=link
  when: galaxie_qmail_server_install_qmailctl
  tags: qmailctl

- name: delete "/usr/local/bin/qmailctl"
  file:
    path="/usr/local/bin/qmailctl"
    state=absent
  when: not galaxie_qmail_server_install_qmailctl
  tags: qmailctl