---
- name: Create temp file {{ galaxie_dnscache_server_dnsroots_global_file }}.XXXXXXXXX
  command: mktemp {{ galaxie_dnscache_server_dnsroots_global_file }}.XXXXXXXXX
  changed_when: False
  register: tmp_file

- name: test if we can resolv "{{ galaxie_dnscache_server_host_for_test }}" by default
  shell: "host {{ galaxie_dnscache_server_host_for_test }}"
  changed_when: False
  register: ResolverCheck

- name: Seed dnsroots
  shell: "dnsip `dnsqr ns . | awk '/answer:/ { print $5; }' |sort`  > {{ tmp_file.stdout }}"
  changed_when: False
  register: SeedDnsroot

- name: Stat of {{ galaxie_dnscache_server_dnsroots_global_file }}
  stat:
    path="{{ galaxie_dnscache_server_dnsroots_global_file }}"
  register: galaxie_dnscache_server_dnsroots_global_file

- name: "Stat of {{ tmp_file.stdout }}"
  stat:
    path={{ tmp_file.stdout }}
  register: galaxie_dnscache_server_dnsroots_global_tmp_file

- name: Update {{ galaxie_dnscache_server_dnsroots_global_file }}
  command: cp {{ tmp_file.stdout }} {{ galaxie_dnscache_server_dnsroots_global_file.stat.path }}
  when: "'{{ galaxie_dnscache_server_dnsroots_global_file.stat.checksum }}' != '{{ galaxie_dnscache_server_dnsroots_global_tmp_file.stat.checksum }}'"

- name: Update dnscache dnsroots list
  command: cp {{ galaxie_dnscache_server_dnsroots_global_file.stat.path }} {{ galaxie_dnscache_server_supervise_dir }}/{{ galaxie_dnscache_server_service_name }}/root/servers/@
  when: "'{{ galaxie_dnscache_server_dnsroots_global_file.stat.checksum }}' != '{{ galaxie_dnscache_server_dnsroots_global_tmp_file.stat.checksum }}'"
  notify:
    - restart service

- name: Delete {{ tmp_file.stdout }}
  file: path={{ tmp_file.stdout }} state=absent
  changed_when: False
  always_run: true
