---
# Openssl auto signed certificate
# http://www.xfiles.dk/guide-on-how-to-run-qmail-with-smtp-ssl/
- name: previous SSL keys and setting"
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_sqmail_ssl_dir }}/{{ glx_sqmail_control_me }}.key"
    - "{{ glx_sqmail_ssl_dir }}/{{ glx_sqmail_control_me }}.pem"
    - "{{ glx_sqmail_dir }}/control/servercert.pem"
  when: glx_sqmail_openssl_key_gen and glx_sqmail_openssl_use_self_signed_cert

- name: generate {{ glx_ucspi_ssl_dh_bits }} bits dh parameter "{{ glx_ucspi_ssl_dh_parameter_file }}" fle
  shell: openssl dhparam -out {{ glx_sqmail_ssl_dir }}/dh{{ glx_ucspi_ssl_dh_bits }}.pem {{ glx_ucspi_ssl_dh_bits }}
    creates={{ glx_sqmail_ssl_dir }}/dh{{ glx_ucspi_ssl_dh_bits }}.pem
  when: glx_sqmail_openssl_key_gen and glx_sqmail_openssl_use_self_signed_cert

- name: auto signed rsa:{{ glx_sqmail_openssl_key_bit }} key, valide for {{ glx_sqmail_openssl_key_days }} days , to "{{ glx_sqmail_dir }}/control/servercert.pem"
  shell:  openssl req -newkey rsa:{{ glx_sqmail_openssl_key_bit }} -x509 -nodes -days {{ glx_sqmail_openssl_key_days }} -out {{ glx_sqmail_control_me }}.pem -keyout {{ glx_sqmail_control_me }}.key -subj "{{ glx_sqmail_openssl_subj }}"
    chdir="{{ glx_sqmail_ssl_dir }}"
  when: glx_sqmail_openssl_key_gen and glx_sqmail_openssl_use_self_signed_cert

- name: check "{{ glx_sqmail_dir }}/control/servercert.pem" permissions
  file:
    path="{{ glx_sqmail_dir }}/control/servercert.pem"
    owner=root
    group={{ glx_sqmail_qmail_group }}
    mode=0640
  with_items:
    - "{{ glx_sqmail_ssl_dir }}/dh{{ glx_ucspi_ssl_dh_bits }}.pem"
    - "{{ glx_sqmail_ssl_dir }}/{{ glx_sqmail_control_me }}.pem"
    - "{{ glx_sqmail_ssl_dir }}/{{ glx_sqmail_control_me }}.key"
  when: glx_sqmail_openssl_key_gen and glx_sqmail_openssl_use_self_signed_cert