---
# Inspiration:
# http://qmailrocks.thibs.com/qmail-configure.php
# http://www.lifewithqmail.com/lwq.html#configuration

- name: Set "{{ glx_sqmail_control_defaultdelivery }}" as default mailbox type for mbox type
  template:
    src="control/defaultdelivery.j2"
    dest="{{ glx_sqmail_dir }}/control/defaultdelivery"
    owner="root"
    group="root"
    mode=0644

- name: Set "{{ glx_sqmail_control_spfbehavior }}" as value between 1 and 6 to enable SPF checks
  template:
    src="control/spfbehavior.j2"
    dest="{{ glx_sqmail_dir }}/control/spfbehavior"
    owner="root"
    group="root"
    mode=0644

- name: Set "{{ glx_sqmail_control_bouncefrom }}" as bounce sender
  template:
    src="control/bouncefrom.j2"
    dest="{{ glx_sqmail_dir }}/control/bouncefrom"
    owner="root"
    group="root"
    mode=0644

### Fast Config
- name: set "{{ glx_sqmail_control_defaultdomain }}" as default domain name
  template:
    src="control/defaultdomain.j2"
    dest="{{ glx_sqmail_dir }}/control/defaultdomain"
    owner="root"
    group="root"
    mode=0644

- name: set "{{ glx_sqmail_control_plusdomain }}" as domain substituted for trailing '+'
  template:
    src="control/plusdomain.j2"
    dest="{{ glx_sqmail_dir }}/control/plusdomain"
    owner="root"
    group="root"
    mode=0644

#### Don't know look to prevent a bug

- name: update the memory to 32MB to avoid memory related errors
  template:
    src="control/conf-common.j2"
    dest="{{ glx_sqmail_dir }}/control/conf-common"
    owner="root"
    group="root"
    mode=0644

#### ctl from s/qmail source
- name: set qmtpd rules {{ glx_sqmail_dir }}/control/rules.qmtpd.txt
  template:
    src="control/rules.qmtpd.txt.j2"
    dest="{{ glx_sqmail_dir }}/control/rules.qmtpd.txt"
    owner="root"
    group="root"
    mode=0644

- name: update {{ glx_sqmail_dir }}/control/rules.qmtpd.cdb
  shell: tcprules rules.qmtpd.cdb rules.qmtpd.tmp < rules.qmtpd.txt
    chdir="{{ glx_sqmail_dir }}/control"
  changed_when: false