---

#### ctl from s/qmail source
- name: set qmtpd rules {{ glx_sqmail_dir }}/control/rules.qmtpd.txt
  template:
    src="control/rules.qmtpd.txt.j2"
    dest="{{ glx_sqmail_dir }}/control/rules.qmtpd.txt"
    owner="root"
    group="root"
    mode=0644

- name: update {{ glx_sqmail_dir }}/control/rules.qmtpd.cdb
  shell: tcprules rules.qmtpd.cdb rules.qmtpd.tmp < rules.qmtpd.txt
    chdir="{{ glx_sqmail_dir }}/control"
  changed_when: false