---
- name: install "{{ glx_prefix_dir }}/bin/sqmailctl" script
  template:
    src=sqmailctl.j2
    dest="{{ glx_prefix_dir }}/bin/sqmailctl"
    mode=0750
    owner=root
    group=root
  when: glx_sqmail_install_sqmailctl
  tags: sqmailctl

- name: delete "{{ glx_prefix_dir }}/bin/sqmailctl"
  file:
    path="{{ glx_prefix_dir }}/bin/sqmailctl"
    state=absent
  when: not glx_sqmail_install_sqmailctl
  tags: sqmailctl
