---
- name: uninstall libcdb1
  apt:
    pkg={{ item }}
    state=absent
  with_items:
    - libcdb1

- name: check {{ glx_slashpackage_dir }} directory
  file:
    path="{{ glx_slashpackage_dir }}"
    state=directory
    mode=1755

- name: check {{ glx_cdb_source_dir }} directory
  file:
    path="{{ glx_cdb_source_dir }}"
    state=directory

- name: delete "{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}.{{ glx_cdb_extension }}"
  file:
    path="{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}.{{ glx_cdb_extension }}"
    state=absent
  when: glx_cdb_force_install

- name: get "{{ glx_cdb_download_url }}"
  get_url:
    url="{{ glx_cdb_download_url }}"
    dest={{ glx_cdb_source_dir }}
    sha256sum=1919577799a50c080a8a05a1cbfa5fa7e7abc823d8d7df2eeb181e624b7952c5
  register: glx_cdb_source_download

- name: delete "{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}" directory
  file:
    path="{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}"
    state=absent
  when: glx_cdb_source_download.changed

- name: unarchive {{ glx_cdb_source_download.dest }}
  unarchive:
    src="{{ glx_cdb_source_download.dest }}"
    dest="{{ glx_cdb_source_dir }}"
    copy=no
  when: glx_cdb_source_download.changed

- name: send cdb-0.75.errno.patch to "{{ glx_cdb_source_dir }}"
  copy:
    src=cdb-0.75.errno.patch
    dest="{{ glx_cdb_source_dir }}/cdb-0.75.errno.patch"
  when: glx_cdb_source_download.changed

- name: apply cdb-0.75.errno.patch
  shell: patch < {{ glx_cdb_source_dir }}/cdb-0.75.errno.patch
    chdir="{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}"
  changed_when: false
  when: glx_cdb_source_download.changed

- name: build {{ glx_cdb_app_name }} on "{{ glx_cdb_source_dir }}" directory
  shell: make
    chdir="{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}"
  changed_when: false

- name: install {{ glx_cdb_app_name }}
  shell: make setup check
    chdir="{{ glx_cdb_source_dir }}/{{ glx_cdb_app_name }}"
  changed_when: false

## mkauth.j2 - https://qmail.jms1.net/scripts/mkauth.j2.shtml
#- name: installing the perl CDB_File module
#  cpanm: name=CDB_File
#  tags: cdb
#
#- name: installing the perl Getopt::Std module
#  cpanm: name=Getopt::Std
#  tags: cdb
#
#- name: resets permissions in Perl's default library path so that everything is owned by root ...
#  script: pfix
#  changed_when: false
#  tags: cdb
#
#- name: check is mkauth is present
#  template:
#    src=mkauth.j2
#    dest=/usr/local/bin/mkauth
#    owner=root
#    group=root
#    mode=0755
#  tags: cdb
#
#- name: list user
#  shell: /usr/local/bin/mkauth | /usr/local/bin/cdbmake-12 {{ galaxie_qmail_server_qmail_dir }}/control/new.cdb {{ galaxie_qmail_server_qmail_dir }}/control/new.tmp
#  changed_when: false
#  tags: cdb
#
#- name: check "{{ galaxie_qmail_server_qmail_dir }}/control/servercert.pem" permissions
#  file:
#    path="{{ galaxie_qmail_server_qmail_dir }}/control/new.cdb"
#    owner=root
#    group={{ galaxie_qmail_server_nofiles_group }}
#    mode=0640
#  changed_when: false
#  tags: cdb
#
#- name: mv {{ galaxie_qmail_server_qmail_dir }}/control/new.cdb {{ galaxie_qmail_server_qmail_dir }}/control/auth.cdb
#  shell: mv {{ galaxie_qmail_server_qmail_dir }}/control/new.cdb {{ galaxie_qmail_server_qmail_dir }}/control/auth.cdb
#  changed_when: false
#  tags: cdb