---
- name: install packages for ucspi-ssl building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - libssl-dev
    - libperl-dev

- name: check {{ galaxie_qmail_server_slashpackage_dir }} directory
  file:
    path="{{ galaxie_qmail_server_slashpackage_dir }}"
    state=directory
    mode=1755

- name: check {{ galaxie_qmail_server_ucspi_ssl_source_dir }} directory
  file:
    path="{{ galaxie_qmail_server_ucspi_ssl_source_dir }}"
    state=directory

- name: delete "{{ galaxie_qmail_server_ucspi_ssl_source_dir }}/{{ galaxie_qmail_server_ucspi_ssl_source_name }}.{{ galaxie_qmail_server_ucspi_ssl_source_extension }}"
  file:
    path="{{ galaxie_qmail_server_ucspi_ssl_source_dir }}/{{ galaxie_qmail_server_ucspi_ssl_source_name }}.{{ galaxie_qmail_server_ucspi_ssl_source_extension }}"
    state=absent
  when: galaxie_qmail_server_ucspi_ssl_force_install

- name: get "{{ galaxie_qmail_server_ucspi_ssl_source_url }}"
  get_url:
    url="{{ galaxie_qmail_server_ucspi_ssl_source_url }}"
    dest={{ galaxie_qmail_server_ucspi_ssl_source_dir }}
    sha256sum=9f3bcf66546b433b089f6f340d243065beb801b97d4026e54dd586f0022b5f1e
  register: galaxie_qmail_server_ucspi_ssl_download

- name: delete "{{ galaxie_qmail_server_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b" directory
  file:
    path="{{ galaxie_qmail_server_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
    state=absent
  when: galaxie_qmail_server_ucspi_ssl_download.changed

- name: unarchive {{ galaxie_qmail_server_ucspi_ssl_download.dest }}
  unarchive:
    src="{{ galaxie_qmail_server_ucspi_ssl_download.dest }}"
    dest="{{ galaxie_qmail_server_slashpackage_dir }}"
    copy=no
  when: galaxie_qmail_server_ucspi_ssl_download.changed

- name: fixe permissions
  file:
    path="{{ galaxie_qmail_server_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
    owner="root"
    group="root"
    recurse=yes
  when: galaxie_qmail_server_ucspi_ssl_download.changed

- name: check "{{ galaxie_qmail_server_ucspi_ssl_certificates_dir }}" directory
  file:
    path="{{ galaxie_qmail_server_ucspi_ssl_certificates_dir }}"
    owner=root
    group=root
    state=directory
    mode=0755

- name: generate {{ galaxie_qmail_server_ucspi_ssl_dh_bits }} bits dh parameter "{{ galaxie_qmail_server_ucspi_ssl_dh_parameter_file }}" fle
  shell: openssl dhparam -out {{ galaxie_qmail_server_ucspi_ssl_dh_parameter_file }} {{ galaxie_qmail_server_ucspi_ssl_dh_bits }}
    creates=/etc/ssl/certs/dhparam.pem

- name: update src/conf-dhfile to reflect "{{ galaxie_qmail_server_ucspi_ssl_dh_parameter_file }}" DH parameter file.
  replace:
    dest="{{ galaxie_qmail_server_ucspi_ssl_conf_dhfile }}"
    regexp="^/usr/local/ssl/pem/dh1024.pem"
    replace="{{ galaxie_qmail_server_ucspi_ssl_dh_parameter_file }}"

- name: check src/conf-dhfile
  lineinfile:
    dest="{{ galaxie_qmail_server_ucspi_ssl_conf_dhfile }}"
    line="{{ galaxie_qmail_server_ucspi_ssl_dh_parameter_file }}"
    state=present

- name: update src/conf-cadir for point to "{{ galaxie_qmail_server_ucspi_ssl_certificates_dir }}".
  replace:
    dest="{{ galaxie_qmail_server_ucspi_ssl_conf_cadir }}"
    regexp="^/usr/local/ssl/certs"
    replace="{{ galaxie_qmail_server_ucspi_ssl_certificates_dir }}"

- name: check src/conf-cadir
  lineinfile:
    dest="{{ galaxie_qmail_server_ucspi_ssl_conf_cadir }}"
    line="{{ galaxie_qmail_server_ucspi_ssl_certificates_dir }}"
    state=present

- name: package/install
  shell: package/install
    chdir="{{ galaxie_qmail_server_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
  when: galaxie_qmail_server_ucspi_ssl_download.changed

- name: package/man
  shell: package/man
    chdir="{{ galaxie_qmail_server_slashpackage_dir }}/host/superscript.com/net/ucspi-ssl-0.95b"
  when: galaxie_qmail_server_ucspi_ssl_download.changed