---
- name: uninstall qmails debian packages
  apt:
    pkg={{ item }}
    state=absent
  with_items:
    - qmail-run
    - qmail-tools
    - qmail
    - qmail-uids-gids
    - dot-forward

- name: install require packages for s/qmail building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - libssl-dev
    - libperl-dev
    - daemontools
    - daemontools-run

- name: check {{ glx_slashpackage_dir }} directory
  file:
    path="{{ glx_slashpackage_dir }}"
    state=directory
    mode=1755

- name: check {{ glx_sqmail_source_dir }} directory
  file:
    path="{{ glx_sqmail_source_dir }}"
    state=directory

- name: delete "{{ glx_sqmail_source_dir }}/{{ glx_sqmail_source_name }}.{{ glx_sqmail_source_extension }}"
  file:
    path="{{ glx_sqmail_source_dir }}/{{ glx_sqmail_source_name }}.{{ glx_sqmail_source_extension }}"
    state=absent
  when: glx_sqmail_force_install

- name: get "{{ glx_sqmail_source_url }}"
  get_url:
    url="{{ glx_sqmail_source_url }}"
    dest={{ glx_sqmail_source_dir }}
    sha256sum=5501a984d83d9f0826c2d497522090f6335049be1442be74d6492dee76c735a7
  register: glx_sqmail_download

- name: delete "{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_source_name }}" directory
  file:
    path="{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_source_name }}"
    state=absent
  when: glx_sqmail_download.changed

- name: unarchive {{ glx_sqmail_download.dest }}
  unarchive:
    src="{{ glx_sqmail_download.dest }}"
    dest="{{ glx_slashpackage_dir }}"
    copy=no
  when: glx_sqmail_download.changed

- name: fixe permissions
  file:
    path="{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_source_name }}"
    owner="root"
    group="root"
    recurse=yes
  when: glx_sqmail_download.changed

# conf-ld -- loader options to be adjusted (for i386; AMD64 normaly default)
- name: check DEB_BUILD_ARCH
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  when: ansible_os_family == "Debian"
  register: DEB_BUILD_ARCH
  changed_when: false

# send conf-* files
- name: check conf-*
  template:
    src="sqmail/{{ item }}.j2"
    dest="{{ glx_sqmail_conf_thing_dir }}/{{ item }}"
  with_items:
    - "conf-break"
    - "conf-cc"
    - "conf-delivery"
    - "conf-djbdns"
    - "conf-groups"
    - "conf-home"
    - "conf-ids"
    - "conf-instances"
    - "conf-ld"
    - "conf-log"
    - "conf-man"
    - "conf-patrn"
    - "conf-qmq"
    - "conf-spawn"
    - "conf-split"
    - "conf-svcdir"
    - "conf-ucspissl"
    - "conf-users"

# send scripts
- name: check scripts
  template:
    src="sqmail/service/{{ item }}.j2"
    dest="{{ glx_sqmail_service_scripts_dir }}/{{ item }}"
  with_items:
    - "run_log"
    - "run_pop3d"
    - "run_pop3sd"
    - "run_qmqpd"
    - "run_qmtpd"
    - "run_qmtpsd"
    - "run_send"
    - "run_smtpd"
    - "run_smtpsd"
    - "run_smtpsub"
    - "ssl.env"

# send package dir
- name: check package dir
  template:
    src="sqmail/package/{{ item }}.j2"
    dest="{{ glx_sqmail_package_dir }}/{{ item }}"
  with_items:
    - "service"
    - "services=d"

- name: package/install
  shell: package/install
    chdir="{{ glx_slashpackage_dir }}/mail/sqmail/{{ glx_sqmail_source_name }}"
  when: glx_sqmail_download.changed