---
- name: uninstall ucspi-tcp-ipv6 and ucspi-tcp packages
  apt:
    pkg={{ item }}
    state=absent
  with_items:
    - ucspi-tcp-ipv6
    - ucspi-tcp
    - ucspi-proxy
    - ucspi-unix

- name: install packages for ucspi-ssl building
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - libssl-dev
    - libperl-dev

- name: check {{ glx_slashpackage_dir }} directory
  file:
    path="{{ glx_slashpackage_dir }}"
    state=directory
    mode=1755

- name: check {{ glx_ucspi_tcp6_source_dir }} directory
  file:
    path="{{ glx_ucspi_tcp6_source_dir }}"
    state=directory

- name: delete "{{ glx_ucspi_tcp6_source_dir }}/{{ glx_ucspi_tcp6_source_name }}.{{ glx_ucspi_tcp6_source_extension }}"
  file:
    path="{{ glx_ucspi_tcp6_source_dir }}/{{ glx_ucspi_tcp6_source_name }}.{{ glx_ucspi_tcp6_source_extension }}"
    state=absent
  when: glx_ucspi_tcp6_force_install

- name: get "{{ glx_ucspi_tcp6_source_url }}"
  get_url:
    url="{{ glx_ucspi_tcp6_source_url }}"
    dest="{{ glx_ucspi_tcp6_source_dir }}"
    sha256sum="b0f6df425c2f3e90c89a94c501414834ea1bc0b66b8ba381fda8ca02f25d1608"
  register: glx_ucspi_tcp6_download

- name: delete "{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00" directory
  file:
    path="{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00"
    state=absent
  when: glx_ucspi_tcp6_download.changed

- name: unarchive {{ glx_ucspi_tcp6_download.dest }}
  unarchive:
    src="{{ glx_ucspi_tcp6_download.dest }}"
    dest="{{ glx_slashpackage_dir }}"
    copy=no
  when: glx_ucspi_tcp6_download.changed

- name: fixe permissions
  file:
    path="{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00"
    owner="root"
    group="root"
    recurse=yes
  when: glx_ucspi_tcp6_download.changed

- name: check DEB_BUILD_ARCH_BITS
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  when: ansible_os_family == "Debian"
  register: DEB_BUILD_ARCH_BITS
  changed_when: false

# send conf-* files
- name: check conf-*
  template:
    src="ucspi-tcp6/src/{{ item }}.j2"
    dest="{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00/src/{{ item }}"
  with_items:
    - "conf-cc"
    - "conf-ld"

- name: package/install
  shell: package/install
    chdir="{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00"
  when: glx_ucspi_tcp6_download.changed

- name: package/man
  shell: package/man
    chdir="{{ glx_slashpackage_dir }}/host/ucspi-tcp6-1.00"
  when: glx_ucspi_tcp6_download.changed