# the big picture : http://www.fehcom.de/images/sqmail_Big_Picture.pdf
# Requirements
- include: config-services-stop.yml

- include: install-cdb.yml
  tags: install-cdb

- include: install-ucspi-tcp6.yml
  tags: install-ucspi-tcp6, install

- include: install-ucspi-ssl.yml
  tags: install-ucspi-ssl, install

- include: install-sqmail.yml
  tags: install-sqmail, install

- include: install-sqmailctl.yml
  tags: install-sqmailctl, install

## Initital setting
#- include: config.yml
#  tags: config
#- include: config-alias.yml
#  tags: alias
#
#- include: install-mta.yml
#  tags: install
#
## qmail-send
#- include: config-send-service.yml
#  when: galaxie_qmail_server_config_send
#  tags: config, config-qmail-send
#
## qmail-smtp
#- include: config-smtpd-service.yml
#  when: galaxie_qmail_server_config_smtpd
#  tags: config, config-qmail-smtpd
#
## smtpd
#- include: config-smtpd-ipv4.yml
#  when: galaxie_qmail_server_config_smtpd_ipv4
#  tags: config
#- include: remove-smtpd-ipv4.yml
#  when: not galaxie_qmail_server_config_smtpd_ipv4
#- include: config-smtpd-ipv6.yml
#  tags: config
#  when: galaxie_qmail_server_config_smtpd_ipv6
#- include: remove-smtpd-ipv6.yml
#  when: not galaxie_qmail_server_config_smtpd_ipv6
#
## smtpsd
#- include: config-openssl.yml
#  when: galaxie_qmail_server_config_smtpsd_ipv4 or galaxie_qmail_server_config_smtpsd_ipv6
#  tags: config






#svc:{{ glx_sqmail_service_smtp.name }}:{{ glx_sqmail_service_smtp.directory }}:{{ glx_sqmail_service_smtp.script }}
#svc:{{ glx_sqmail_service_smtps.name }}:{{ glx_sqmail_service_smtps.directory }}:{{ glx_sqmail_service_smtps.script }}
#svc:{{ glx_sqmail_service_submission.name }}:{{ glx_sqmail_service_submission.directory }}:{{ glx_sqmail_service_submission.script }}
#svc:{{ glx_sqmail_service_pop3.name }}:{{ glx_sqmail_service_pop3.directory }}:{{ glx_sqmail_service_pop3.script }}
#svc:{{ glx_sqmail_service_pop3s.name }}:{{ glx_sqmail_service_pop3s.directory }}:{{ glx_sqmail_service_pop3s.script }}
#svc:{{ glx_sqmail_service_qmqp.name }}:{{ glx_sqmail_service_qmqp.directory }}:{{ glx_sqmail_service_qmqp.script }}
#svc:{{ glx_sqmail_service_qmtp.name }}:{{ glx_sqmail_service_qmtp.directory }}:{{ glx_sqmail_service_qmtp.script }}
#svc:{{ glx_sqmail_service_qmtps.name }}:{{ glx_sqmail_service_qmtps.directory }}:{{ glx_sqmail_service_qmtps.script }}

- include: uninstall-a-service.yml
  vars:
     glx_service_to_check= "{{ item }}"
  with_items: glx_sqmail_aviable_services_list
  tags: cleanup


## finilize
#- include: config-man.yml
#  tags: config-man
#- include: config-services-register.yml
#- include: install-qfixpermissions.yml
#  tags: install
