# the big picture : http://www.fehcom.de/images/sqmail_Big_Picture.pdf
# Stop everything for permit to overwrite few binary
- include: services-stop.yml
  tags: install

# Intall the requirements
- include: install-cdb.yml
  tags: install-cdb, install

- include: install-ucspi-tcp6.yml
  tags: install-ucspi-tcp6, install

- include: install-ucspi-ssl.yml
  tags: install-ucspi-ssl, install

- include: install-sqmail.yml
  tags: install-sqmail, install

- include: install-sqmailctl.yml
  tags: install-sqmailctl, install

## Initital setting
- include: config-controls.yml
  tags: controls, config

- include: config-qmail-send.yml
  tags: controls, config

- include: config-qmail-smtpd.yml
  tags: controls, config

- include: config-qmail-remote.yml
  tags: controls, config

- include: config-qmail-inject.yml
  tags: controls, config

- include: config-alias.yml
  tags: alias, config

#- include: install-mta.yml
#  tags: install

#- include: config-openssl.yml
#  when: galaxie_qmail_server_config_smtpsd_ipv4 or galaxie_qmail_server_config_smtpsd_ipv6
#  tags: config






#svc:{{ glx_sqmail_service_smtp.name }}:{{ glx_sqmail_service_smtp.directory }}:{{ glx_sqmail_service_smtp.script }}
#svc:{{ glx_sqmail_service_smtps.name }}:{{ glx_sqmail_service_smtps.directory }}:{{ glx_sqmail_service_smtps.script }}
#svc:{{ glx_sqmail_service_submission.name }}:{{ glx_sqmail_service_submission.directory }}:{{ glx_sqmail_service_submission.script }}
#svc:{{ glx_sqmail_service_pop3.name }}:{{ glx_sqmail_service_pop3.directory }}:{{ glx_sqmail_service_pop3.script }}
#svc:{{ glx_sqmail_service_pop3s.name }}:{{ glx_sqmail_service_pop3s.directory }}:{{ glx_sqmail_service_pop3s.script }}
#svc:{{ glx_sqmail_service_qmqp.name }}:{{ glx_sqmail_service_qmqp.directory }}:{{ glx_sqmail_service_qmqp.script }}
#svc:{{ glx_sqmail_service_qmtp.name }}:{{ glx_sqmail_service_qmtp.directory }}:{{ glx_sqmail_service_qmtp.script }}
#svc:{{ glx_sqmail_service_qmtps.name }}:{{ glx_sqmail_service_qmtps.directory }}:{{ glx_sqmail_service_qmtps.script }}

#- include: uninstall-a-service.yml
#  vars:
#     glx_service_to_check= "{{ item }}"
#  with_items: glx_sqmail_aviable_services_list
#  tags: cleanup



## finilize
- include: services-cleanup.yml
  tags: cleanup, install-sqmail, install

- include: cleanup.yml
  tags: cleanup, install-sqmail, install