---
# send
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}"
  register: send
  when: not glx_sqmail_service_send.enable

- name: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}/log
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}/log
  when: not glx_sqmail_service_send.enable and send.stat.exists

- name: remove {{ glx_sqmail_service_send.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_send.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_send.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_send.directory }}"
  when: not glx_sqmail_service_send.enable and send.stat.exists

# smtp
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }}"
  register: smtp
  when: not glx_sqmail_service_smtp.enable

- name: svc -dt {{ glx_sqmail_service_smtp.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }}/log
  when: not glx_sqmail_service_smtp.enable and smtp.stat.exists

- name: remove {{ glx_sqmail_service_smtp.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_smtp.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_smtp.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_smtp.directory }}"
  when: not glx_sqmail_service_smtp.enable and smtp.stat.exists

# smtps
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }}"
  register: smtps
  when: not glx_sqmail_service_smtps.enable

- name: svc -dt {{ glx_sqmail_service_smtps.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }}/log
  when: not glx_sqmail_service_smtps.enable and smtps.stat.exists

- name: remove {{ glx_sqmail_service_smtps.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_smtps.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_smtps.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_smtps.directory }}"
  when: not glx_sqmail_service_smtps.enable and smtps.stat.exists

# submission
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }}"
  register: submission
  when: not glx_sqmail_service_submission.enable

- name: svc -dt {{ glx_sqmail_service_submission.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }}/log
  when: not glx_sqmail_service_submission.enable and submission.stat.exists

- name: remove {{ glx_sqmail_service_submission.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_submission.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_submission.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_submission.directory }}"
  when: not glx_sqmail_service_submission.enable and submission.stat.exists

# pop3
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }}"
  register: pop3
  when: not glx_sqmail_service_pop3.enable

- name: svc -dt {{ glx_sqmail_service_pop3.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }}/log
  when: not glx_sqmail_service_pop3.enable and pop3.stat.exists

- name: remove {{ glx_sqmail_service_pop3.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_pop3.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_pop3.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_pop3.directory }}"
  when: not glx_sqmail_service_pop3.enable and pop3.stat.exists

# pop3s
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }}"
  register: pop3s
  when: not glx_sqmail_service_pop3s.enable

- name: svc -dt {{ glx_sqmail_service_pop3s.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }}/log
  when: not glx_sqmail_service_pop3s.enable and pop3s.stat.exists

- name: remove {{ glx_sqmail_service_pop3s.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_pop3s.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_pop3s.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_pop3s.directory }}"
  when: not glx_sqmail_service_pop3s.enable and pop3s.stat.exists

# qmqp
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }}"
  register: qmqp
  when: not glx_sqmail_service_qmqp.enable

- name: svc -dt {{ glx_sqmail_service_qmqp.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }}/log
  when: not glx_sqmail_service_qmqp.enable and qmqp.stat.exists

- name: remove {{ glx_sqmail_service_qmqp.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmqp.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_qmqp.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_qmqp.directory }}"
  when: not glx_sqmail_service_qmqp.enable and qmqp.stat.exists

# qmtp
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }}"
  register: qmtp
  when: not glx_sqmail_service_qmtp.enable

- name: svc -dt {{ glx_sqmail_service_qmtp.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }}/log
  when: not glx_sqmail_service_qmtp.enable and qmtp.stat.exists

- name: remove {{ glx_sqmail_service_qmtp.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmtp.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_qmtp.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_qmtp.directory }}"
  when: not glx_sqmail_service_qmtp.enable and qmtp.stat.exists

# qmtps
###############################################################################
- name: test {{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }}
  stat:
    path="{{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }}"
  register: qmtps
  when: not glx_sqmail_service_qmtps.enable

- name: svc -dt {{ glx_sqmail_service_qmtps.directory }}
  shell: svc -dt {{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }} {{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }}/log
  when: not glx_sqmail_service_qmtps.enable and qmtps.stat.exists

- name: remove {{ glx_sqmail_service_qmtps.directory }} files and directory
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }}/log"
    - "{{ glx_service_dir }}/{{ glx_sqmail_service_qmtps.directory }}"
    - "{{ glx_supervise_dir }}/{{ glx_sqmail_service_qmtps.directory }}"
    - "{{ glx_multilog_dir}}/{{ glx_sqmail_service_qmtps.directory }}"
  when: not glx_sqmail_service_qmtps.enable and qmtps.stat.exists


