---
- name: delete previous {{ glx_ndjbdns_source_dir }} source directory
  file:
    path="{{ glx_ndjbdns_source_dir }}"
    state=absent
  when: glx_ndjbdns_force_install

- name: check {{ glx_ndjbdns_source_dir }} directory
  file:
    path="{{ glx_ndjbdns_source_dir }}"
    state=directory

- name: install required software
  action: apt pkg="{{item}}" state=installed
  with_items:
    - git
    - checkinstall

- name: get n-djbdns sources from {{ glx_ndjbdns_git_repo }} git repository
  git:
    repo="{{ glx_ndjbdns_git_repo }}"
    dest="{{ glx_ndjbdns_source_dir }}"
    update=yes

- name: fixe https://github.com/pjps/ndjbdns/issues/14
  shell: aclocal && autoconf && automake --add-missing
    chdir="{{ glx_ndjbdns_source_dir }}"

- name: ./configure --prefix={{ glx_ndjbdns_prefix }} --sysconfdir={{ glx_ndjbdns_sysconfdir }}
  shell: ./configure --prefix={{ glx_ndjbdns_prefix }} --sysconfdir={{ glx_ndjbdns_sysconfdir }}
    chdir="{{ glx_ndjbdns_source_dir }}"

- name: make
  shell: make
    chdir="{{ glx_ndjbdns_source_dir }}"

- name: exec make install
  shell: make install
    chdir="{{ glx_ndjbdns_source_dir }}"