---
- include: install-ndjbdns.yml
  tags: install

- include: config-dnscache.yml
  tags: config, config-dnscache

- include: update-roots.yml
  tags: config, upgrade-roots

- include: config-tinydns.yml
  tags: config, config-tinydns