
- name: Install unattended-upgrades
  apt: pkg={{ item }} state=latest
  with_items:
    - unattended-upgrades
    - apt-listchanges

- name: check {{ galaxie_apt_unattended_periodic_file }}
  template:
    src=periodic.j2
    dest={{ galaxie_apt_unattended_periodic_file }}
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades

- name: check {{ galaxie_apt_unattended_unattended_upgrades_file }}
  template:
    src=unattended-upgrades.j2
    dest={{ galaxie_apt_unattended_unattended_upgrades_file }}
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades

- name: start unattended-upgrades
  service:
    name=unattended-upgrades
    state=started
    enabled=yes
  changed_when: false

- name: remove /etc/cron.d/apt-upgrade
  file:
    path: /etc/cron.d/apt-upgrade
    state: absent

- name: remove /etc/apt/apt.conf.d/10periodic
  file:
    path: /etc/apt/apt.conf.d/10periodic
    state: absent

- name: start unattended-upgrades
  service:
    name=unattended-upgrades
    state=restarted
    enabled=yes

- name: check {{ galaxie_apt_unattended_listchanges_file }}
  template:
    src=listchanges_conf.j2
    dest={{ galaxie_apt_unattended_listchanges_file }}
    owner=root
    group=root
    mode=0644