
- name: Install unattended-upgrades
  apt: pkg={{ item }} state=latest
  with_items:
    - unattended-upgrades

- name: check periodic configuration
  template:
    src=periodic.j2
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades

- name: check unattended-upgrades configuration
  template:
    src=upgrades.j2
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades

- name: start unattended-upgrades
  service:
    name=unattended-upgrades
    state=started
    enabled=yes
  changed_when: false

- name: remove /etc/cron.d/apt-upgrade
  file:
    path: /etc/cron.d/apt-upgrade
    state: absent