---
- hosts: apt-cacher-ng-server
  user: zoe
  sudo: yes

  vars_files:
    - "galaxie-vars.yml"

  tasks:

  handlers:
    - name: restart apt-cacher-ng
      service:
        name=apt-cacher-ng
        state=restarted

