- hosts: pabx-servers

  tasks:
    - name : Stop Asterisk
      service:
        name=asterisk
        state=stopped

    - name : Start Asterisk
      service:
        name=asterisk
        state=started
