---
- hosts: galaxie
  user: zoe
  sudo: yes

  vars_files:
    - "galaxie-vars.yml"

  tasks:
    - name: activate debian jessie main contrib non-free repository
      apt_repository:
        repo="{{ item }}"
        state=present
      with_items:
        - deb http://ftp.fr.debian.org/debian/ jessie main non-free contrib
        - deb-src http://ftp.fr.debian.org/debian/ jessie main non-free contrib
        - deb http://security.debian.org/ jessie/updates main non-free contrib
        - deb-src http://security.debian.org/ jessie/updates main non-free contrib
        - deb http://ftp.fr.debian.org/debian/ jessie-updates main non-free contrib
        - deb-src http://ftp.fr.debian.org/debian/ jessie-updates main non-free contrib

    - name: update apt cache
      apt: update_cache=yes

    - name: desired packages are present
      apt:
        pkg="{{item}}"
        state=installed
      with_items:
        - bash-completion
        - dnsutils
        - htop
        - git
        - wget
        - vim
        - mc
        - ntp
        - rsync
        - sshfs
        - screen
        - minicom
        - task-spooler
        - cron
        - findutils

    - name: undesired packages are absent
      apt:
        pkg="{{item}}"
        state=absent
        purge=yes
      with_items:
        - nano
        - ntpdate
        - nfs-common
        - nfs-kernel-server
        - rpcbind
        - vim-tiny
        - emacs
        - samba
        - samba-common


# TODO: configure NTP as client of ntp servers stated in host.inventory if not in group ntp