- hosts: desktops
  user: little_alice
  sudo: true

  vars_files:
    - "galaxie-vars.yml"

  tasks:

    - name: Check directory
      file:
        path="{{item}}"
        owner=root
        group=root
        state=directory
        mode=0755
      with_items:
        - "{{ galaxie.cache_dir }}"
        - "{{ galaxie.applications_dir }}"

    - name: Get Stats {{ galaxie.cache_dir }}/{{ galaxie.thunderbird.filename }}
      stat: path="{{ galaxie.cache_dir }}/{{ galaxie.thunderbird.filename }}"
      register: thunderbird_source_file_stat

    - name: Download {{ galaxie.thunderbird.repo_url }}/{{ galaxie.thunderbird.filename }}
      get_url:
        url="{{ galaxie.thunderbird.repo_url }}/{{ galaxie.thunderbird.filename }}"
        dest="{{ galaxie.cache_dir }}/{{ galaxie.thunderbird.filename }}"
        mode=0440
        validate_certs=no
      when: not thunderbird_source_file_stat.stat.exists

    - name: Delete previus version
      file:
        path={{ galaxie.applications_dir }}/thunderbird
        state=absent

    - name: Unarchive {{ galaxie.cache_dir }}/{{ galaxie.thunderbird.filename }}
      unarchive: src={{ galaxie.cache_dir }}/{{ galaxie.thunderbird.filename }} dest={{ galaxie.applications_dir }} copy=no

    - name: set permissions of {{ galaxie.applications_dir }}/thunderbird
      file:
        path={{ galaxie.applications_dir }}/thunderbird
        owner=root
        group=root
        state=directory
        mode=0755

    - name: set permissions of {{ galaxie.applications_dir }}/thunderbird/
      file:
        path={{ galaxie.applications_dir }}/thunderbird
        owner=root
        group=root
        recurse=yes

    - name: delete previus /usr/bin/thunderbird
      file:
        path=/usr/bin/thunderbird
        state=absent

    - name: Create symbolic link
      file: src={{ galaxie.applications_dir }}/thunderbird/thunderbird dest=/usr/bin/thunderbird state=link

    - name: creat /usr/share/applications/thunderbird.desktop is ok
      template:
        src=templates/thunderbird.desktop.j2
        dest=/usr/share/applications/thunderbird.desktop
        backup=no