- hosts: zoe_test
  sudo: true
  vars:
     project_dir: /usr/src/galaxie_zoe_voice
     acoustic_model_url: http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20F0%20Broadcast%20News%20Acoustic%20Model/lium_french_f0.tar.gz/download
     acoustic_model_file: lium_french_f0.tar.gz

     trigram_language_model_url: http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/french3g62K.lm.dmp.bz2/download
     trigram_language_model_file: french3g62K.lm.dmp.bz2

     pronunciation_dictionary_url: http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/frenchWords62K.dic/download
     pronunciation_dictionary_file: frenchWords62K.dic

     ## MBROLA Variable ##
     # http://tcts.fpms.ac.be/synthesis/mbrola/
     # mbrola GNU/Linux binary
     mbrola_linux_binary_url: http://tcts.fpms.ac.be/synthesis/mbrola/bin/pclinux/mbr301h.zip
     mbrola_linux_binary_file: mbr301h.zip
     # fr1: French Male (4.4Mb)    Faculte Polytech. De Mons
     mbrola_voices_fr1_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr1/fr1-990204.zip
     mbrola_voices_fr1_file: fr1-990204.zip
     # fr2: French Female (4.8Mb)    Celine Egea
     mbrola_voices_fr2_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr2/fr2-980806.zip
     mbrola_voices_fr2_file: fr2-980806.zip
     # fr3: French Male (4.8Mb)    Babel Technology
     mbrola_voices_fr3_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr3/fr3-990324.zip
     mbrola_voices_fr3_file: fr3-990324.zip
     # fr4: French Female (5.4Mb)  Babel Technology
     mbrola_voices_fr4_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr4/fr4-990521.zip
     mbrola_voices_fr4_file: fr4-990521.zip
     # fr5: French Belgian (4.8Mb) Faculte Polytech. De Mons
     mbrola_voices_fr5_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr5/fr5-991020.zip
     mbrola_voices_fr5_file: fr5-991020.zip  
     # fr6: French Male (4.4Mb)    Faculte Polytech. De Mons
     mbrola_voices_fr6_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr6/fr6-010330.zip
     mbrola_voices_fr6_file: fr6-010330.zip
     # fr7: French Belgian (3.7Mb) Faculte Polytech. De Mons
     mbrola_voices_fr7_url: http://tcts.fpms.ac.be/synthesis/mbrola/dba/fr7/fr7-010330.zip
     mbrola_voices_fr7_file: fr7-010330.zip
     # mbrola install directory
     mbrola_install_directory: /opt/mbrola

  tasks:
   - name: Update Apt
     apt: update_cache=yes cache_valid_time=3600

   - name: Install required software
     action: apt pkg={{item}} state=installed
     with_items:
      - pocketsphinx
      - libpocketsphinx1
      - python-pyaudio
      - python-aiml
      - python-pocketsphinx
      - gstreamer0.10-pulseaudio
      - gstreamer0.10-pocketsphinx
      - libao4
      - libasound2-plugins
      - libgconfmm-2.6-1c2
      - libglademm-2.4-1c2a
      - libpulse-mainloop-glib0
      - libpulse0
      - libsox-fmt-pulse
      - paman
      - paprefs
      - pavucontrol
      - pavumeter
      - pulseaudio
      - pulseaudio-esound-compat
      - pulseaudio-module-bluetooth
      - pulseaudio-module-gconf
      - pulseaudio-module-jack
      - pulseaudio-module-lirc
      - pulseaudio-module-x11
      - pulseaudio-module-zeroconf
      - pulseaudio-utils
      - oss-compat
      - speech-dispatcher
      - espeak

   - name: Remove unrequired software
     action: apt pkg={{item}} state=absent
     with_items:
      - pulseaudio-module-lirc-dbg
      - pulseaudio-dbg
      - libpulse0-dbg
      - libpulse-dev
      - pulseaudio-module-zeroconf-dbg
      - libpulse-mainloop-glib0-dbg
      - pulseaudio-esound-compat-dbg
      

   - name: Ask for pocketsphinx pkg-config path
     action: shell pkg-config --variable=modeldir pocketsphinx
     register: pocketsphinx_pkg_config_path

   - name: Creates directory project_dir
     action: file dest={{ project_dir }}  state=directory

### accoustic model ###

   - name: stats lium_french_f0.tar.gz
     stat: path={{ project_dir }}/{{ acoustic_model_file }}
     register: acoustic_model_file_stat

   - name: Download lium_french_f0 French model sources
     get_url: url={{ acoustic_model_url }} dest={{ project_dir }}/{{ acoustic_model_file }}
     when: not acoustic_model_file_stat.stat.exists

   - name: Untar lium_french_f0.tar.gz
     unarchive: src={{ project_dir }}/{{ acoustic_model_file }} dest={{ project_dir }} copy=no
     when: acoustic_model_file_stat.stat.exists

   - name: Restore root permission
     file: path={{ project_dir }} owner=root group=root recurse=yes

   - name: Creates directory hmm/fr_FR
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/hmm/fr_FR  state=directory

   - name: Delete directory hmm/fr_FR/french_f0
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/hmm/fr_FR/french_f0  state=absent

   - name: Move french_f0/* to  pocketsphinx/hmm/fr_FR/french_f0 directory
     command: mv {{ project_dir }}/lium_french_f0 {{ pocketsphinx_pkg_config_path.stdout }}/hmm/fr_FR/french_f0

### trigram language ###

   - name: stats french3g62K.lm.dmp.bz2
     stat: path={{ project_dir }}/{{ trigram_language_model_file }}
     register: trigram_language_model_file_stat

   - name: Download french3g62K.lm.dmp French model sources
     get_url: url={{ trigram_language_model_url }} dest={{ project_dir }}/{{ trigram_language_model_file }}
     when: not trigram_language_model_file_stat.stat.exists

   - name: unbip2 french3g62K.lm.dmp.bz2
     command: chdir={{ project_dir }} bunzip2 -k {{ trigram_language_model_file }}
     when: trigram_language_model_file_stat.stat.exists

   - name: Restore root permission
     file: path={{ project_dir }} owner=root group=root recurse=yes

   - name: Creates directory /lm/fr_FR
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR  state=directory

   - name: Delete pocketsphinx/lm/fr_FR/french3g62K.lm.dmp
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR/french3g62K.lm.dmp state=absent

   - name: Move french3g62K.lm.dmp to  pocketsphinx/lm/fr_FR/ directory
     command: mv {{ project_dir }}/french3g62K.lm.dmp {{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR/

### pronunciation dictionary (lexicon) ###

   - name: stats frenchWords62K.dic
     stat: path={{ project_dir }}/{{ pronunciation_dictionary_file }}
     register: pronunciation_dictionary_file_stat

   - name: Download pronunciation dictionary
     get_url: url={{ pronunciation_dictionary_url }} dest={{ project_dir }}/{{ pronunciation_dictionary_file }}
     when: not pronunciation_dictionary_file_stat.stat.exists

   - name: Restore root permission
     file: path={{ project_dir }} owner=root group=root recurse=yes

   - name: Creates directory /lm/fr_FR
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR  state=directory

   - name: Delete pocketsphinx/lm/fr_FR/frenchWords62K.dic
     action: file dest={{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR/frenchWords62K.dic state=absent

   - name: Move frenchWords62K.dic to  pocketsphinx/lm/fr_FR/frenchWords62K.dic
     command: cp {{ project_dir }}/frenchWords62K.dic {{ pocketsphinx_pkg_config_path.stdout }}/lm/fr_FR/

### Configure pulseaudio ###

##  Setting up ALSA ###
   - name: stats /etc/asound.conf.ORIG
     stat: path=/etc/asound.conf.ORIG
     register: asound_conf_ORIG

   - name: Backup /etc/asound.conf to /etc/asound.conf.ORIG
     command: cp -pf /etc/asound.conf /etc/asound.conf.ORIG
     when: not asound_conf_ORIG.stat.exists

   - name: Push a new asound.conf file
     template: src=templates/asound.conf dest=/etc/asound.conf owner=root group=root mode=0644

## Set up the PulseAudio daemon for network connections  ##
   - name: stats /etc/pulse/system.pa.ORIG
     stat: path=/etc/pulse/system.pa.ORIG
     register: pulse_system_pa_ORIG

   - name: cp -fvp /etc/pulse/system.pa to /etc/pulse/system.pa.ORIG
     command: cp -fvp /etc/pulse/system.pa /etc/pulse/system.pa.ORIG
     when: not pulse_system_pa_ORIG.stat.exists

   - name: Set up the PulseAudio daemon for network connections
     lineinfile:
      dest=/etc/pulse/system.pa
      regexp="^load-module module-native-protocol-tcp auth-ip-acl="
      line="load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;192.168.0.0/16 auth-anonymous=1"
      state=present

   - name: Set up the Zeroconf module for PulseAudio daemon
     lineinfile:
      dest=/etc/pulse/system.pa
      line="load-module module-zeroconf-publish"
      state=present

## Change default sound driver from alsa to pulseaudio  ##
   - name: stats /etc/libao.conf.ORIG
     stat: path=/etc/libao.conf.ORIG
     register: libao_conf_ORIG

   - name: cp -fvp /etc/libao.conf /etc/libao.conf.ORIG
     command: cp -fvp /etc/libao.conf /etc/libao.conf.ORIG
     when: not libao_conf_ORIG.stat.exists

   - name: Change default sound driver from alsa to pulseaudio
     lineinfile:
      dest=/etc/libao.conf
      regexp="^default_driver="
      line="default_driver=pulse"
      state=present

   - name: stats /etc/pulse/daemon.conf.ORIG
     stat: path=/etc/pulse/daemon.conf.ORIG
     register: daemon_conf_ORIG

   - name: cp -fvp /etc/pulse/daemon.conf /etc/pulse/daemon.conf.ORIG
     command: cp -fvp /etc/pulse/daemon.conf /etc/pulse/daemon.conf.ORIG
     when: not daemon_conf_ORIG.stat.exists

   - name: Set "high-priority = yes" on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; high-priority ="
      line="high-priority = yes"
      state=present

   - name: Set "nice-level = 5"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; nice-level ="
      line="nice-level = 5"
      state=present

   - name: Set "exit-idle-time = -1"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; exit-idle-time ="
      line="exit-idle-time = -1"
      state=present

   - name: Set "resample-method = src-sinc-medium-quality"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; resample-method ="
      line="resample-method = src-sinc-medium-quality"
      state=present

   - name: Set "default-sample-format = s16le"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; default-sample-format ="
      line="default-sample-format = s16le"
      state=present

   - name: Set "default-sample-rate = 48000"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; default-sample-rate ="
      line="default-sample-rate = 48000"
      state=present

   - name: Set "default-sample-channels = 2"  on /etc/pulse/daemon.conf file
     lineinfile:
      dest=/etc/pulse/daemon.conf
      regexp="^; default-sample-channels ="
      line="default-sample-channels = 2"
      state=present

### MBROLA installation ###
## Source: http://bothari.free.fr/weblog/post/Ubuntu-Text-to-Speech-%28TTS%29

   - name: Test mbrola_linux_binary_file
     stat: path={{ project_dir }}/{{ mbrola_linux_binary_file }}
     register: mbrola_linux_binary_file_stat
   - name: Test mbrola_voices_fr1_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr1_file }}
     register: mbrola_voices_fr1_file_stat
   - name: Test mbrola_voices_fr2_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr2_file }}
     register: mbrola_voices_fr2_file_stat
   - name: Test mbrola_voices_fr3_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr3_file }}
     register: mbrola_voices_fr3_file_stat
   - name: Test mbrola_voices_fr4_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr4_file }}
     register: mbrola_voices_fr4_file_stat
   - name: Test mbrola_voices_fr5_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr5_file }}
     register: mbrola_voices_fr5_file_stat
   - name: Test mbrola_voices_fr6_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr6_file }}
     register: mbrola_voices_fr6_file_stat
   - name: Test mbrola_voices_fr7_file  
     stat: path={{ project_dir }}/{{ mbrola_voices_fr7_file }}
     register: mbrola_voices_fr7_file_stat

   - name: Download mbrola_linux_binary_file
     get_url: url={{ mbrola_linux_binary_url }} dest={{ project_dir }}/{{ mbrola_linux_binary_file }}
     when: not mbrola_linux_binary_file_stat.stat.exists
   - name: Download mbrola_voices_fr1_file
     get_url: url={{ mbrola_voices_fr1_url }} dest={{ project_dir }}/{{ mbrola_voices_fr1_file }}
     when: not mbrola_voices_fr1_file_stat.stat.exists
   - name: Download mbrola_voices_fr2_file
     get_url: url={{ mbrola_voices_fr2_url }} dest={{ project_dir }}/{{ mbrola_voices_fr2_file }}
     when: not mbrola_voices_fr2_file_stat.stat.exists
   - name: Download mbrola_voices_fr3_file
     get_url: url={{ mbrola_voices_fr3_url }} dest={{ project_dir }}/{{ mbrola_voices_fr3_file }}
     when: not mbrola_voices_fr3_file_stat.stat.exists
   - name: Download mbrola_voices_fr4_file
     get_url: url={{ mbrola_voices_fr4_url }} dest={{ project_dir }}/{{ mbrola_voices_fr4_file }}
     when: not mbrola_voices_fr4_file_stat.stat.exists
   - name: Download mbrola_voices_fr5_file
     get_url: url={{ mbrola_voices_fr5_url }} dest={{ project_dir }}/{{ mbrola_voices_fr5_file }}
     when: not mbrola_voices_fr5_file_stat.stat.exists
   - name: Download mbrola_voices_fr6_file
     get_url: url={{ mbrola_voices_fr6_url }} dest={{ project_dir }}/{{ mbrola_voices_fr6_file }}
     when: not mbrola_voices_fr6_file_stat.stat.exists
   - name: Download mbrola_voices_fr7_file
     get_url: url={{ mbrola_voices_fr7_url }} dest={{ project_dir }}/{{ mbrola_voices_fr7_file }}
     when: not mbrola_voices_fr7_file_stat.stat.exists

   - name: Creates mbrola_install_directory
     action: file dest={{ mbrola_install_directory }} state=directory
   - name: Creates /usr/share/mbrola directory
     action: file dest=/usr/share/mbrola state=directory
   - name: Creates mbrola_voices_fr4 directory
     action: file dest=/usr/share/mbrola/fr4 state=directory


   - name: Unarchive mbrola_linux_binary_file
     unarchive: src={{ project_dir }}/{{ mbrola_linux_binary_file }} dest={{ mbrola_install_directory }} copy=no
   - name: Unarchive mbrola_voices_fr1_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr1_file }} dest=/usr/share/mbrola/ copy=no
   - name: Unarchive mbrola_voices_fr2_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr2_file }} dest=/usr/share/mbrola/ copy=no
   - name: Unarchive mbrola_voices_fr3_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr3_file }} dest=/usr/share/mbrola/ copy=no
   - name: Unarchive mbrola_voices_fr4_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr4_file }} dest=/usr/share/mbrola/fr4 copy=no
   - name: Unarchive mbrola_voices_fr5_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr5_file }} dest=/usr/share/mbrola/ copy=no
   - name: Unarchive mbrola_voices_fr6_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr6_file }} dest=/usr/share/mbrola/ copy=no
   - name: Unarchive mbrola_voices_fr7_file
     unarchive: src={{ project_dir }}/{{ mbrola_voices_fr7_file }} dest=/usr/share/mbrola/ copy=no         

         
   - name: Restore root permission
     file: path={{ mbrola_install_directory }}  owner=root group=root recurse=yes
   - name: Enable executable permission for mbrola binary
     file: path={{ mbrola_install_directory }}/mbrola-linux-i386  owner=root group=root mode=0755
   - name: Create symlink to /usr/bin/mbrola
     file: src={{ mbrola_install_directory }}/mbrola-linux-i386 dest=/usr/bin/mbrola state=link

### speech-dispatcher ###
   - name: stats /etc/speech-dispatcher/speechd.conf.ORIG
     stat: path=/etc/speech-dispatcher/speechd.conf.ORIG
     register: speechd_conf_ORIG

   - name: cp -fvp /etc/speech-dispatcher/speechd.conf /etc/speech-dispatcher/speechd.conf.ORIG
     command: cp -fvp /etc/speech-dispatcher/speechd.conf /etc/speech-dispatcher/speechd.conf.ORIG
     when: not speechd_conf_ORIG.stat.exists

   - name: Set DefaultVoiceType  "FEMALE1"
     lineinfile:
      dest=/etc/speech-dispatcher/speechd.conf
      regexp='^DefaultVoiceType'
      line='DefaultVoiceType  "FEMALE1"'
      insertafter='^# DefaultVoiceType  "MALE1"'
      state=present

   - name: Set DefaultLanguage  "fr"
     lineinfile:
      dest=/etc/speech-dispatcher/speechd.conf
      regexp='^DefaultLanguage'
      line='DefaultLanguage  "fr"'
      insertafter='^# DefaultLanguage "en"'
      state=present

   - name: Set AddModule "espeak-generic" "sd_generic" "espeak-generic.conf"
     lineinfile:
      dest=/etc/speech-dispatcher/speechd.conf
      regexp='^AddModule "espeak-generic" "sd_generic" "espeak-generic.conf"'
      line='AddModule "espeak-generic" "sd_generic" "espeak-generic.conf"'
      insertafter='#AddModule "pico"        "sd_pico"     "pico.conf"'
      state=present

   - name: DefaultModule espeak-generic
     lineinfile:
      dest=/etc/speech-dispatcher/speechd.conf
      regexp='^DefaultModule'
      line='DefaultModule espeak-generic'
      state=present

