---
- hosts: apt-cacher-ng-server
  user: zoe
  sudo: yes

  vars_files:
    - "galaxie-vars.yml"

  tasks:
    - name: Install packages apt-cacher-ng ed
      apt:
        pkg="{{item}}"
        state=installed
      with_items:
        - apt-cacher-ng
        - ed

    - name: Creat {{ galaxie.apt_cacher_ng.cache_dir }} directory
      file:
        path={{ galaxie.apt_cacher_ng.cache_dir }}
        owner={{ galaxie.apt_cacher_ng.user }}
        group={{ galaxie.apt_cacher_ng.group }}
        state=directory
        mode=0755

    - name: Write /etc/apt-cacher-ng/acng.conf
      template:
        src=templates/apt-cacher-ng-server.conf.j2
        dest=/etc/apt-cacher-ng/acng.conf
        backup=yes
      notify:
        - restart apt-cacher-ng

  handlers:
    - name: restart apt-cacher-ng
      service:
        name=apt-cacher-ng
        state=restarted

