- hosts: desktops
  user: little_alice
  sudo: true

  vars_files:
    - "galaxie-vars.yml"

  tasks:
    - name: Check directory
      file:
        path="{{item}}"
        owner=root
        group=root
        state=directory
        mode=0755
      with_items:
        - "{{ galaxie.cache_dir }}"
        - "{{ galaxie.applications_dir }}"

    - name: Get Stats {{ galaxie.cache_dir }}/{{ galaxie.firefox.filename }}
      stat: path={{ galaxie.cache_dir }}/{{ galaxie.firefox.filename }}
      register: firefox_source_file_stat

    - name: Download {{ galaxie.firefox.repo_url }}/{{ galaxie.firefox.filename }}
      get_url:
        url="{{ galaxie.firefox.repo_url }}/{{ galaxie.firefox.filename }}"
        dest="{{ galaxie.cache_dir }}/{{ galaxie.firefox.filename }}"
        mode=0440
        validate_certs=no
      when: not firefox_source_file_stat.stat.exists

    - name: Delete previus version
      file:
        path={{ galaxie.applications_dir }}/firefox
        state=absent

    - name: Unarchive {{ galaxie.cache_dir }}/{{ galaxie.firefox.filename }}
      unarchive:
        src={{ galaxie.cache_dir }}/{{ galaxie.firefox.filename }}
        dest={{ galaxie.applications_dir }}
        copy=no

    - name: Set permissions of {{ galaxie.applications_dir }}/firefox
      file:
        path={{ galaxie.applications_dir }}/firefox
        owner=root
        group=root
        state=directory
        mode=0755

    - name: set permissions of {{ galaxie.applications_dir }}/firefox/
      file:
        path={{ galaxie.applications_dir }}/firefox
        owner=root
        group=root
        recurse=yes

    - name: Delete preview /usr/bin/firefox
      file:
        path=/usr/bin/firefox
        state=absent

    - name: Create symbolic link
      file: src={{ galaxie.applications_dir }}/firefox/firefox dest=/usr/bin/firefox state=link

    - name: Creat /usr/share/applications/firefox.desktop is ok
      template:
        src=templates/firefox.desktop.j2
        dest=/usr/share/applications/firefox.desktop
        backup=no