- hosts: galaxie
  sudo: true
  vars:
   - toplevel_timeservers: ['192.168.1.71']

  tasks:
   - name: Update Apt
     apt: update_cache=yes cache_valid_time=3600

   - name: Remove not ntpdate
     action: apt pkg={{item}} state=absent purge=yes
     with_items:
      - ntpdate

   - name: Install required software
     action: apt pkg={{item}} state=installed
     with_items:
      - ntp

   - name: Copy over the NTP configuration
     template: src=templates/ntp.conf dest=/etc/ntp.conf
     notify: restart ntp

  handlers:
      - name: restart ntp
        service: name=ntp state=restarted
