- hosts: galaxie_pvr

  sudo: true

  vars:
    build_dir: /usr/src/galaxie_dvbhdhomerun_build_
    git_src: https://github.com/h0tw1r3/dvbhdhomerun.git

  tasks:
   - name: Update Apt
     apt: update_cache=yes cache_valid_time=3600
   - name: Install required software
     action: apt pkg={{item}} state=installed
     with_items:
      - debhelper
      - cmake
      - libhdhomerun-dev
      - dkms
      - module-assistant
      - build-essential
      - make
      - bzip2
      - linux-headers-amd64
      - curl
      - hdhomerun-config
      - libhdhomerun-dev
      - libhdhomerun1

   - action: shell date '+%F'
     register: mydate
 
   - name: Delete previous installation
     file: path={{ build_dir  }}{{ mydate.stdout }} state=absent

   - name: Creates directory {{ build_dir  }}{{ mydate.stdout }}
     action: file dest={{ build_dir  }}{{ mydate.stdout }}  state=directory

   - name: Download Git master of dvbhdhomerun
     shell: chdir={{ build_dir  }}{{ mydate.stdout }} git clone {{ git_src  }}
   
   - name: Building ...
     shell: chdir={{ build_dir  }}{{ mydate.stdout }}/dvbhdhomerun dpkg-buildpackage -b

   - action: shell ls {{ build_dir  }}{{ mydate.stdout }}/dvbhdhomerun-dkms_*.deb
     register: dkms_path

   - action: shell ls {{ build_dir  }}{{ mydate.stdout }}/dvbhdhomerun-source_*.deb
     register: source_path

   - action: shell ls {{ build_dir  }}{{ mydate.stdout }}/dvbhdhomerun-utils_*.deb
     register: utils_path


   - name: Install Package dvbhdhomerun-source
     apt: deb={{ source_path.stdout }}

   - name: Install Package dvbhdhomerun-dkms
     apt: deb={{ dkms_path.stdout }}

   - name: Install Package dvbhdhomerun-utils
     apt: deb={{ utils_path.stdout }}

   - name: Copy dvbhdhomerun configuration
     template: src=templates/dvbhdhomerun dest=/etc/dvbhdhomerun
     notify: restart dvbhdhomerun-utils

  handlers:
   - name: restart dvbhdhomerun-utils
     service: name=dvbhdhomerun-utils state=restarted
