---
- hosts: servers
  user: zoe
  sudo: yes

  vars_files:
    - "galaxie-vars.yml"

  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: desired packages are present
      apt:
        pkg="{{item}}"
        state=installed
      with_items:
        - bash-completion
        - dnsutils
        - htop
        - module-assistant
        - git
        - wget
        - vim
        - emacs
        - mc
        - ntp
        - rsync
        - sshfs
        - screen
        - minicom

    - name: undesired packages are absent
      apt:
        pkg="{{item}}"
        state=absent
        purge=yes
      with_items:
        - nano
        - ntpdate
        - nfs-common
        - nfs-kernel-server
        - rpcbind


# TODO: configure NTP as client of ntp servers stated in host.inventory if not in group ntp