---
###############
### * Hosts ###
###############
#- include: openssh-server.yml
#- include: openssh-client.yml
#- include: apt-get-client.yml
###############
### Servers ###
###############

### Frist deal with DNS / NTP / DHCP
#- include: dnscache-server.yml
#- include: dnscache-server-update.yml
#- include: ntp-server.yml

### Configure Apt
#- include: apt-cacher-ng-server.yml

### Configure a LAMP (Linux Apache MySQL PHP)
#- include: apache-server.yml
#- include: mysql-server.yml

###############
### Host ###
###############
### Frist deal with DNS / NTP / DHCP
- include: dnscache-client.yml
#- include: ntp-client.yml
#- include: apt-cacher-ng-client.yml
#- include: common.yml
#- include: banner.yml

# Desktops
#- include: desktops-base.yml
#- include: gnome-setting.yml
#- include: mozilla-firefox.yml
#- include: mozilla-thunderbird.yml


