- hosts: galaxie
  user: zoe
  sudo: true

  tasks:
    - name: Start apt-get update
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_distribution == 'Debian'

    - name: Start apt-get upgrade
      apt: upgrade=full
      when: ansible_distribution == 'Debian'