- hosts: pabx-servers
  user: little_alice
  sudo: true

  tasks:
    - name : Stop Asterisk
      service:
        name=asterisk
        state=stopped

    - name : Start Asterisk
      service:
        name=asterisk
        state=started
