---

- name: ntpdate is absent
  apt:
    pkg=ntpdate
    state=absent
    purge=yes

- name: ntp is present
  apt:
    pkg=ntp
    state=present

- name: ntp time source {{ galaxie_ntp_server_ntp_referrals }}
  when: "{{ 'internal-machines' in group_names }}"
  template:
    src="ntp-server-internal.conf.j2"
    dest="/etc/ntp.conf"
  notify: restart ntp

- name: ntp time source {{ galaxie_ntp_server_ntp_pool }}
  when: "{{ 'external-machines' in group_names }}"
  template:
    src=ntp-server-external.conf.j2
    dest=/etc/ntp.conf
  notify: restart ntp

- name: remove dhcp-ntp files
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - "/etc/dhcp/dhclient-exit-hooks.d/ntp"
    - "/var/lib/ntp/ntp.conf.dhcp"
  notify: restart ntp
