- hosts: ntp-servers
  user: zoe
  sudo: true

  vars_files:
    - "galaxie-vars.yml"

  tasks:
    - name: ntpdate is absent
      apt:
        pkg=ntpdate
        state=absent
        purge=yes

    - name: ntp is present
      apt:
        pkg=ntp
        state=present

    - name: ntp is configured
      template:
        src=templates/ntp-server.conf.j2
        dest=/etc/ntp.conf
      notify: restart ntp

  handlers:
    - name: restart ntp
      service:
        name=ntp
        state=restarted