---

- name: ntpdate is absent
  apt:
    pkg=ntpdate
    state=absent
    purge=yes

- name: ntp is present
  apt:
    pkg=ntp
    state=present

- name: ntp time source {{ galaxie.ntp.referrals }}
  template:
    src=ntp-server-internal.conf.j2
    dest=/etc/ntp.conf
  notify: restart ntp
  when: inventory_hostname in groups["internal-machines"]

- name: ntp time source {{ galaxie.ntp.pool }}
  template:
    src=ntp-server-external.conf.j2
    dest=/etc/ntp.conf
  notify: restart ntp
  when: inventory_hostname in groups["external-machines"]

- name: remove file /etc/dhcp/dhclient-exit-hooks.d/ntp
  file:
    path=/etc/dhcp/dhclient-exit-hooks.d/ntp
    state=absent
  notify: restart ntp

- name: remove file /var/lib/ntp/ntp.conf.dhcp
  file:
    path=/var/lib/ntp/ntp.conf.dhcp
    state=absent
  notify: restart ntp