---

- name: ntpdate is absent
  apt: pkg=ntpdate state=absent purge=yes

- name: ntp is present
  apt: pkg=ntp state=present

- name: ntp is configured
  template: src=ntp-client.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp


