---

- name: Vim | Check if installed
  action: apt pkg="{{item}}" state=present
  with_items:
    - vim
    - vim-common

- name: Vim | Remove vim-tiny and nano
  apt: pkg="{{item}}" state=absent purge=yes
  with_items:
    - vim-tiny
    - nano

- name: Vim | Check syntax highlighting
  replace:
    dest=/etc/vim/vimrc
    regexp='^\"syntax\s[a-zA-Z0-9_]+|^syntax\s[a-zA-Z0-9_]+'
    replace='syntax on'

- name: Vim | Enable syntax highlighting
  lineinfile:
    dest=/etc/vim/vimrc
    line="syntax on"
    state=present

- name: Vim | Check dark background
  replace:
    dest=/etc/vim/vimrc
    regexp='^\"set background=[a-zA-Z0-9_]+|^set background=[a-zA-Z0-9_]+'
    replace='set background=dark'

- name: Vim | Using set background=dark
  lineinfile:
    dest=/etc/vim/vimrc
    line="set background=dark"
    state=present

- name: Vim | Check tabstop
  replace:
    dest=/etc/vim/vimrc
    regexp='^\"set tabstop=[0-9]+|^set tabstop=[0-9]+'
    replace='set tabstop=4'

- name: Vim | Using tabstop=4
  lineinfile:
    dest=/etc/vim/vimrc
    line="set tabstop=4"
    state=present

- name: Vim | Check shiftwidth
  replace:
    dest=/etc/vim/vimrc
    regexp='^\"set shiftwidth=[0-9]+|^set shiftwidth=[0-9]+'
    replace='set shiftwidth=4'

- name: Vim | Using shiftwidth=4
  lineinfile:
    dest=/etc/vim/vimrc
    line="set shiftwidth=4"
    state=present

- name: Vim | Check expandtab
  replace:
    dest=/etc/vim/vimrc
    regexp='^\"set expandtab|^set expandtab'
    replace='set expandtab'

- name: Vim | Using shiftwidth=4
  lineinfile:
    dest=/etc/vim/vimrc
    line="set expandtab"
    state=present