---
# Configure service to start via Systemd
# https://github.com/aperezdc/perezdecastro.org/blob/master/stash/recipe-running-qmail-send-under-systemd.markdown
# http://mario.raval.li/2012/11/30/qmail-systemd/

- name: set statup script "/lib/systemd/system/{{ galaxie_qmail_server_service_send }}.service"
  template:
    src="qmail-send.service.j2"
    dest="/lib/systemd/system/{{ galaxie_qmail_server_service_send }}.service"
    mode=0644
  tags: qmail-send-service

- name: enable {{ galaxie_qmail_server_service_send }}
  service:
    name="{{ galaxie_qmail_server_service_send }}"
    state=started
    enabled=yes
  tags: qmail-send-service